"""Code generated by scripts/gen-clients.sh — DO NOT EDIT.
Source: clients/openapi.json (Crucible Gateway 1.0.0)
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional, TypedDict, cast
from urllib.parse import quote, urlencode, urlsplit, urlunsplit

from .errors import ApiError

_API_KEY_HEADER = "X-API-Key"


_MAX_ERROR_BODY = 64 * 1024


def _parse_error_envelope(status: int, raw: bytes) -> ApiError:
    try:
        envelope = json.loads(raw) if raw else None
    except ValueError:
        # Catches json.JSONDecodeError (malformed JSON), UnicodeDecodeError
        # (json.loads decodes bytes itself per RFC 8259 UTF-8/16/32 sniffing,
        # so a non-UTF-8 body raises this before JSONDecodeError), and the
        # bare ValueError CPython's int/str conversion limit raises for a
        # pathologically long integer literal (int string conversion length
        # limit, tightened for CVE-2020-10735) — all three are ValueError
        # subclasses, so catching it directly covers every "not valid JSON"
        # shape without surfacing a raw codec/parsing exception to the caller.
        return ApiError("UNKNOWN", f"HTTP {status} (invalid JSON)", False, "", status)
    error = envelope.get("error") if isinstance(envelope, dict) else None
    if not isinstance(error, dict) or not error.get("code"):
        return ApiError("UNKNOWN", f"HTTP {status} (missing error code)", False, "", status)
    return ApiError(
        code=str(error.get("code", "UNKNOWN")),
        message=str(error.get("message", "")),
        retryable=bool(error.get("retryable", False)),
        request_id=str(error.get("request_id", "")),
        status=status,
    )


def _api_error_from_http_error(e: "urllib.error.HTTPError") -> ApiError:
    # Read up to _MAX_ERROR_BODY + 1 bytes; the extra byte lets an oversized
    # body be detected explicitly instead of silently truncated, mirroring
    # the Go client's checkError bound.
    try:
        try:
            raw = e.read(_MAX_ERROR_BODY + 1)
        except OSError as read_err:
            # Covers both a stalled read (TimeoutError) and a reset/aborted
            # connection (ConnectionResetError, BrokenPipeError, etc. — all
            # OSError subclasses) while reading a non-2xx body; either way
            # this must not leak a raw socket exception past this typed-
            # error path.
            return ApiError("UNKNOWN", f"error reading response body: {read_err}", True, "", e.code)
    finally:
        # HTTPError is itself the response object (a file-like/addinfourl);
        # raise ... from None only suppresses traceback display, it does not
        # drop the reference — ApiError.__context__ keeps this alive (and
        # with it the underlying socket) for as long as the ApiError is, so
        # this closes it explicitly rather than relying on GC timing.
        e.close()
    if len(raw) > _MAX_ERROR_BODY:
        # Mirrors the Go client's checkError exactly: an oversized body is
        # reported as its own error, not truncated-then-parsed — a truncated
        # prefix can still happen to be syntactically valid JSON (e.g. the
        # real envelope followed by padding), which would let an oversized,
        # malformed response control `code`/`retryable` instead of being
        # rejected outright.
        return ApiError("UNKNOWN", f"HTTP {e.code} (error body >{_MAX_ERROR_BODY} bytes)", False, "", e.code)
    return _parse_error_envelope(e.code, raw)

class HealthzResponse(TypedDict):
    status: str


class ReadyzResponse(TypedDict):
    checks: Dict[str, str]
    status: str


class ListErrorsResponseDataItem(TypedDict):
    created_at: str
    error_code: str
    http_status: int
    id: int
    message: str
    operation: str
    request_id: str
    request_payload: Optional[str]

class ListErrorsResponse(TypedDict):
    data: Optional[List[ListErrorsResponseDataItem]]
    has_more: bool
    limit: int
    page: int


class _ListJobsResponseItemsItemRequired(TypedDict):
    created_at: str
    job_id: str
    operation: str
    status: str
    updated_at: str


class ListJobsResponseItemsItem(_ListJobsResponseItemsItemRequired, total=False):
    billable_units: int
    error: Any
    units_label: str

class ListJobsResponse(TypedDict):
    items: Optional[List[ListJobsResponseItemsItem]]
    total: int


class _GetJobResponseRequired(TypedDict):
    created_at: str
    job_id: str
    status: str
    updated_at: str


class GetJobResponse(_GetJobResponseRequired, total=False):
    billable_units: int
    error: Any
    result: Any
    units_label: str


class ListKeysResponseItemsItem(TypedDict):
    created_at: str
    expires_at: Optional[str]
    id: str
    last_used_at: Optional[str]
    name: Optional[str]
    prefix: str

class ListKeysResponse(TypedDict):
    items: Optional[List[ListKeysResponseItemsItem]]
    total: int


class RotateKeyResponse(TypedDict):
    key: str


class GetUsageResponse(TypedDict):
    breakdown: Optional[List[Any]]
    cap: int
    period_end: str
    period_start: str
    plan_id: str
    remaining: int
    total_calls: int
    total_units: int
    used: int


class ListUsageEventsResponseDataItem(TypedDict):
    billable_units: str
    created_at: str
    id: str
    operation: str

class ListUsageEventsResponse(TypedDict):
    data: Optional[List[ListUsageEventsResponseDataItem]]
    has_more: bool
    limit: int
    page: int


class ListWebhookEndpointsResponse(TypedDict):
    items: Optional[List[Any]]
    total: int


class _CreateWebhookEndpointResponseRequired(TypedDict):
    active: bool
    created_at: str
    id: str
    secret_hex: str
    url: str


class CreateWebhookEndpointResponse(_CreateWebhookEndpointResponseRequired, total=False):
    subscribed_events: Optional[List[Any]]


class RotateWebhookEndpointSecretResponse(TypedDict):
    secret_hex: str



class Client:
    """Type-safe consumer SDK for the Crucible Gateway API.

    Uses urllib.request from the standard library — zero runtime dependencies.
    Construct with Client(base_url, api_key=...); api_key set here is the
    default sent on every authenticated call and can be overridden per call
    via the api_key parameter on individual methods. timeout (seconds) is
    passed straight through to urllib.request.urlopen on every call; the
    default None means block indefinitely (urllib's own default), matching
    the Go SDK's http.DefaultClient (also no timeout unless the caller
    supplies one) and the TS SDK's bare fetch (also no timeout unless the
    caller wires an AbortSignal) — callers who need a bound must opt in.
    """

    def __init__(
        self, base_url: str, api_key: Optional[str] = None, timeout: Optional[float] = None
    ) -> None:
        # Normalize base_url: strip query, fragment, and credentials, and trim
        # a trailing "/" from the path — mirrors the Go/TS constructors, so a
        # base URL like "https://gw.example?debug=1" cannot silently corrupt
        # every request path built by appending "/v1/..." after it.
        parsed = urlsplit(base_url)
        netloc = parsed.hostname or ""
        # urlsplit().hostname strips the brackets from an IPv6 literal (e.g.
        # "[::1]" -> "::1"); re-add them so the rebuilt authority doesn't
        # collide with the ":<port>" suffix below ("::1:8080" is a different,
        # wrong host — the brackets are what disambiguate host from port).
        if ":" in netloc:
            netloc = f"[{netloc}]"
        if parsed.port:
            netloc += f":{parsed.port}"
        path = parsed.path.rstrip("/")
        self.base_url = urlunsplit((parsed.scheme, netloc, path, "", ""))
        self.default_api_key = api_key
        self.timeout = timeout

    def healthz(self) -> HealthzResponse:
        """GET /healthz (healthz)."""
        raw = self._request("GET", "/healthz", None, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(HealthzResponse, out)

    def readyz(self) -> ReadyzResponse:
        """GET /readyz (readyz)."""
        raw = self._request("GET", "/readyz", None, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(ReadyzResponse, out)

    def invoke_echo(self, payload: Dict[str, Any], api_key: Optional[str] = None) -> Dict[str, Any]:
        """POST /v1/echo (invoke echo)."""
        body = json.dumps(payload, allow_nan=False).encode("utf-8")
        raw = self._request("POST", "/v1/echo", api_key if api_key is not None else self.default_api_key, body)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        if out is None:
            out = {}
        return cast(Dict[str, Any], out)

    def list_errors(self, from_: Optional[str] = None, to: Optional[str] = None, operation: Optional[str] = None, code: Optional[str] = None, page: Optional[int] = None, limit: Optional[int] = None, api_key: Optional[str] = None) -> ListErrorsResponse:
        """GET /v1/errors (list errors)."""
        _params: Dict[str, str] = {}
        if from_ is not None:
            _params["from"] = str(from_)
        if to is not None:
            _params["to"] = str(to)
        if operation is not None:
            _params["operation"] = str(operation)
        if code is not None:
            _params["code"] = str(code)
        if page is not None:
            _params["page"] = str(page)
        if limit is not None:
            _params["limit"] = str(limit)
        path = "/v1/errors"
        if _params:
            path += "?" + urlencode(_params)
        raw = self._request("GET", path, api_key if api_key is not None else self.default_api_key, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(ListErrorsResponse, out)

    def list_jobs(self, page: Optional[int] = None, per_page: Optional[int] = None, status: Optional[str] = None, operation: Optional[str] = None, api_key: Optional[str] = None) -> ListJobsResponse:
        """GET /v1/jobs (list jobs)."""
        _params: Dict[str, str] = {}
        if page is not None:
            _params["page"] = str(page)
        if per_page is not None:
            _params["per_page"] = str(per_page)
        if status is not None:
            _params["status"] = str(status)
        if operation is not None:
            _params["operation"] = str(operation)
        path = "/v1/jobs"
        if _params:
            path += "?" + urlencode(_params)
        raw = self._request("GET", path, api_key if api_key is not None else self.default_api_key, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(ListJobsResponse, out)

    def get_job(self, id: str, api_key: Optional[str] = None) -> GetJobResponse:
        """GET /v1/jobs/{id} (get job)."""
        path = f"/v1/jobs/{quote(str(id), safe='')}"
        raw = self._request("GET", path, api_key if api_key is not None else self.default_api_key, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(GetJobResponse, out)

    def list_keys(self, page: Optional[int] = None, per_page: Optional[int] = None, api_key: Optional[str] = None) -> ListKeysResponse:
        """GET /v1/keys (list keys)."""
        _params: Dict[str, str] = {}
        if page is not None:
            _params["page"] = str(page)
        if per_page is not None:
            _params["per_page"] = str(per_page)
        path = "/v1/keys"
        if _params:
            path += "?" + urlencode(_params)
        raw = self._request("GET", path, api_key if api_key is not None else self.default_api_key, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(ListKeysResponse, out)

    def revoke_key(self, id: str, api_key: Optional[str] = None) -> None:
        """DELETE /v1/keys/{id} (revoke key)."""
        path = f"/v1/keys/{quote(str(id), safe='')}"
        self._request("DELETE", path, api_key if api_key is not None else self.default_api_key, None)
        return None

    def rotate_key(self, id: str, payload: Optional[Dict[str, Any]] = None, api_key: Optional[str] = None) -> RotateKeyResponse:
        """POST /v1/keys/{id}/rotate (rotate key)."""
        if payload is None:
            payload = {}
        body = json.dumps(payload, allow_nan=False).encode("utf-8")
        path = f"/v1/keys/{quote(str(id), safe='')}/rotate"
        raw = self._request("POST", path, api_key if api_key is not None else self.default_api_key, body)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(RotateKeyResponse, out)

    def get_usage(self, api_key: Optional[str] = None) -> GetUsageResponse:
        """GET /v1/usage (get usage)."""
        raw = self._request("GET", "/v1/usage", api_key if api_key is not None else self.default_api_key, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(GetUsageResponse, out)

    def list_usage_events(self, from_: Optional[str] = None, to: Optional[str] = None, operation: Optional[str] = None, page: Optional[int] = None, limit: Optional[int] = None, api_key: Optional[str] = None) -> ListUsageEventsResponse:
        """GET /v1/usage/events (list usage events)."""
        _params: Dict[str, str] = {}
        if from_ is not None:
            _params["from"] = str(from_)
        if to is not None:
            _params["to"] = str(to)
        if operation is not None:
            _params["operation"] = str(operation)
        if page is not None:
            _params["page"] = str(page)
        if limit is not None:
            _params["limit"] = str(limit)
        path = "/v1/usage/events"
        if _params:
            path += "?" + urlencode(_params)
        raw = self._request("GET", path, api_key if api_key is not None else self.default_api_key, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(ListUsageEventsResponse, out)

    def list_webhook_endpoints(self, page: Optional[int] = None, per_page: Optional[int] = None, api_key: Optional[str] = None) -> ListWebhookEndpointsResponse:
        """GET /v1/webhooks/endpoints (list webhook endpoints)."""
        _params: Dict[str, str] = {}
        if page is not None:
            _params["page"] = str(page)
        if per_page is not None:
            _params["per_page"] = str(per_page)
        path = "/v1/webhooks/endpoints"
        if _params:
            path += "?" + urlencode(_params)
        raw = self._request("GET", path, api_key if api_key is not None else self.default_api_key, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(ListWebhookEndpointsResponse, out)

    def create_webhook_endpoint(self, payload: Dict[str, Any], api_key: Optional[str] = None) -> CreateWebhookEndpointResponse:
        """POST /v1/webhooks/endpoints (create webhook endpoint)."""
        body = json.dumps(payload, allow_nan=False).encode("utf-8")
        raw = self._request("POST", "/v1/webhooks/endpoints", api_key if api_key is not None else self.default_api_key, body)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(CreateWebhookEndpointResponse, out)

    def delete_webhook_endpoint(self, id: str, api_key: Optional[str] = None) -> None:
        """DELETE /v1/webhooks/endpoints/{id} (delete webhook endpoint)."""
        path = f"/v1/webhooks/endpoints/{quote(str(id), safe='')}"
        self._request("DELETE", path, api_key if api_key is not None else self.default_api_key, None)
        return None

    def update_webhook_endpoint_subscription(self, id: str, payload: Optional[Dict[str, Any]] = None, api_key: Optional[str] = None) -> None:
        """PATCH /v1/webhooks/endpoints/{id} (update webhook endpoint subscription)."""
        if payload is None:
            payload = {}
        body = json.dumps(payload, allow_nan=False).encode("utf-8")
        path = f"/v1/webhooks/endpoints/{quote(str(id), safe='')}"
        self._request("PATCH", path, api_key if api_key is not None else self.default_api_key, body)
        return None

    def rotate_webhook_endpoint_secret(self, id: str, api_key: Optional[str] = None) -> RotateWebhookEndpointSecretResponse:
        """POST /v1/webhooks/endpoints/{id}/rotate-secret (rotate webhook endpoint secret)."""
        path = f"/v1/webhooks/endpoints/{quote(str(id), safe='')}/rotate-secret"
        raw = self._request("POST", path, api_key if api_key is not None else self.default_api_key, None)
        if raw is None:
            raise ApiError("UNKNOWN", "unexpected 204 No Content for a typed JSON response", False, "", 204)
        out = json.loads(raw)
        return cast(RotateWebhookEndpointSecretResponse, out)

    def _request(
        self, method: str, path: str, api_key: Optional[str], body: Optional[bytes]
    ) -> Optional[bytes]:
        url = self.base_url + path
        headers = {"Accept": "application/json"}
        if body is not None:
            headers["Content-Type"] = "application/json"
        if api_key:
            headers[_API_KEY_HEADER] = api_key
        req = urllib.request.Request(url, data=body, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                if resp.status == 204:
                    return None
                return resp.read()
        except urllib.error.HTTPError as e:
            raise _api_error_from_http_error(e) from None
        except urllib.error.URLError as e:
            # A connect-phase timeout surfaces here as URLError(reason=TimeoutError(...)) —
            # treat it as retryable, consistent with the bare-OSError branch
            # below, instead of lumping it in with genuine connection failures.
            # URLError is itself an OSError subclass, so this must be caught
            # before the generic "except OSError" below, not after.
            timed_out = isinstance(e.reason, TimeoutError)
            message = f"request timed out: {e.reason}" if timed_out else f"connection error: {e.reason}"
            raise ApiError("UNKNOWN", message, timed_out, "", 0) from None
        except OSError as e:
            # A read-phase timeout (TimeoutError) or a reset/aborted connection
            # (ConnectionResetError, BrokenPipeError, etc.) raised bare from
            # resp.read() above — this happens after urlopen() already
            # succeeded, so it is not a URLError, but is equally transient.
            raise ApiError("UNKNOWN", f"error reading response body: {e}", True, "", 0) from None
