// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)

import { ApiError } from "./errors";

export interface HealthzResponse {
  status: string;
}
export interface ReadyzResponse {
  checks: Record<string, string>;
  status: string;
}

export interface ClientOptions {
  /** Override the global fetch implementation (useful in tests). Defaults to globalThis.fetch. */
  fetch?: typeof globalThis.fetch;
  /** Default API key sent as X-API-Key on authenticated requests. */
  apiKey?: string;
}

/**
 * Client is a type-safe consumer SDK for the Crucible Gateway.
 * It uses the runtime's fetch with no additional runtime dependencies.
 */
export class Client {
  private readonly baseURL: string;
  private readonly fetchImpl: typeof globalThis.fetch;
  private readonly defaultApiKey: string | undefined;

  constructor(baseURL: string, options: ClientOptions = {}) {
    // Normalize baseURL: strip query, fragment, and credentials (mirrors Go client).
    let normalizedURL = baseURL;
    try {
      const u = new URL(baseURL);
      u.search = "";
      u.hash = "";
      u.username = "";
      u.password = "";
      normalizedURL = u.toString();
    } catch {
      throw new TypeError(`crucible: invalid baseURL: ${baseURL}`);
    }
    this.baseURL = normalizedURL.replace(/\/+$/u, "");
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.defaultApiKey = options.apiKey;
  }

  /** GET /healthz — healthz. */
  async healthz(): Promise<HealthzResponse> {
    return this.get<HealthzResponse>("/healthz");
  }

  /** GET /readyz — readyz. */
  async readyz(): Promise<ReadyzResponse> {
    return this.get<ReadyzResponse>("/readyz");
  }

  /**
   * POST /v1/echo — invoke echo.
   * @param apiKey - Override the default API key for this call.
   */
  async invokeEcho(payload: Record<string, unknown>, apiKey?: string): Promise<Record<string, unknown>> {
    return this.post<Record<string, unknown>>("/v1/echo", payload, apiKey ?? this.defaultApiKey);
  }

  private async get<T>(path: string, apiKey?: string): Promise<T> {
    const headers: Record<string, string> = { Accept: "application/json" };
    if (apiKey) {
      headers["X-API-Key"] = apiKey;
    }
    const resp = await this.fetchImpl(this.baseURL + path, {
      method: "GET",
      headers,
    });
    if (!resp.ok) {
      throw await ApiError.fromResponse(resp);
    }
    const ct = resp.headers.get("content-type") ?? "";
    if (!ct.includes("application/json")) {
      throw new ApiError(resp.status, "UNKNOWN", `unexpected content-type: ${ct}`);
    }
    return resp.json() as Promise<T>;
  }

  private async post<T>(path: string, body: unknown, apiKey?: string): Promise<T> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      Accept: "application/json",
    };
    if (apiKey) {
      headers["X-API-Key"] = apiKey;
    }
    const resp = await this.fetchImpl(this.baseURL + path, {
      method: "POST",
      headers,
      body: JSON.stringify(body),
    });
    if (!resp.ok) {
      throw await ApiError.fromResponse(resp);
    }
    const ct = resp.headers.get("content-type") ?? "";
    if (!ct.includes("application/json")) {
      throw new ApiError(resp.status, "UNKNOWN", `unexpected content-type: ${ct}`);
    }
    return resp.json() as Promise<T>;
  }
}
