// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)

/** Shape of the gateway error envelope. */
export interface ErrorBody {
  error: {
    code: string;
    message: string;
    retryable?: boolean;
  };
}

/**
 * ApiError is thrown when the gateway returns a non-2xx status.
 * It models the error envelope: {"error":{"code":"...","message":"...","retryable":true}}.
 */
export class ApiError extends Error {
  readonly code: string;
  readonly retryable: boolean | undefined;
  readonly status: number;

  constructor(status: number, code: string, message: string, retryable?: boolean) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.code = code;
    this.retryable = retryable;
    // Restore prototype chain (required when extending built-ins in ES5 targets).
    Object.setPrototypeOf(this, new.target.prototype);
  }

  static async fromResponse(resp: Response): Promise<ApiError> {
    if (resp.bodyUsed) {
      return new ApiError(resp.status, "UNKNOWN", `HTTP ${resp.status} (body already consumed)`);
    }
    let code = "UNKNOWN";
    let message = `HTTP ${resp.status}`;
    let retryable: boolean | undefined;
    try {
      const body = (await resp.json()) as ErrorBody;
      code = body.error.code;
      message = body.error.message;
      retryable = body.error.retryable;
    } catch {
      // body is not valid JSON; keep defaults
    }
    return new ApiError(resp.status, code, message, retryable);
  }
}
