// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)

// Package crucible is a type-safe Go client for the Crucible Gateway API.
// Construct a Client with New; all timeouts are the caller's responsibility.
package crucible

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// Client calls the Crucible Gateway. Construct with New.
type Client struct {
	baseURL *url.URL
	http    *http.Client
}

// New returns a Client targeting baseURL, or an error if baseURL cannot be parsed.
// httpClient defaults to http.DefaultClient when nil. Note: http.DefaultClient has no
// timeout; callers must supply a client with Timeout set or use context.WithTimeout.
// baseURL is normalized: query strings, fragments, and credentials are stripped; trailing
// slashes on the path are removed so that appending spec paths (which start with "/") is correct.
// Any base path prefix (e.g. "/crucible" for a reverse-proxy subpath) is preserved.
func New(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("crucible: invalid baseURL %q: %w", baseURL, err)
	}
	u.RawQuery = ""
	u.Fragment = ""
	u.User = nil
	u.Path = strings.TrimRight(u.Path, "/")
	return &Client{baseURL: u, http: httpClient}, nil
}

// HealthzResponse is returned by Healthz.
type HealthzResponse struct {
	Status string `json:"status"`
}

// ReadyzResponse is returned by Readyz.
type ReadyzResponse struct {
	Checks map[string]string `json:"checks"`
	Status string            `json:"status"`
}

// ListErrorsResponseDataItem is one row of ListErrors's "data" list.
type ListErrorsResponseDataItem struct {
	Created_at      string `json:"created_at"`
	Error_code      string `json:"error_code"`
	Http_status     int64  `json:"http_status"`
	Id              int64  `json:"id"`
	Message         string `json:"message"`
	Operation       string `json:"operation"`
	Request_id      string `json:"request_id"`
	Request_payload string `json:"request_payload"`
}

// ListErrorsResponse is returned by ListErrors.
type ListErrorsResponse struct {
	Data     []ListErrorsResponseDataItem `json:"data"`
	Has_more bool                         `json:"has_more"`
	Limit    int64                        `json:"limit"`
	Page     int64                        `json:"page"`
}

// ListJobsResponseItemsItem is one row of ListJobs's "items" list.
type ListJobsResponseItemsItem struct {
	Billable_units int64  `json:"billable_units"`
	Created_at     string `json:"created_at"`
	Error          any    `json:"error"`
	Job_id         string `json:"job_id"`
	Operation      string `json:"operation"`
	Status         string `json:"status"`
	Units_label    string `json:"units_label"`
	Updated_at     string `json:"updated_at"`
}

// ListJobsResponse is returned by ListJobs.
type ListJobsResponse struct {
	Items []ListJobsResponseItemsItem `json:"items"`
	Total int64                       `json:"total"`
}

// GetJobResponse is returned by GetJob.
type GetJobResponse struct {
	Billable_units int64  `json:"billable_units"`
	Created_at     string `json:"created_at"`
	Error          any    `json:"error"`
	Job_id         string `json:"job_id"`
	Result         any    `json:"result"`
	Status         string `json:"status"`
	Units_label    string `json:"units_label"`
	Updated_at     string `json:"updated_at"`
}

// CancelJobResponse is returned by CancelJob.
type CancelJobResponse struct {
	Billable_units int64  `json:"billable_units"`
	Created_at     string `json:"created_at"`
	Error          any    `json:"error"`
	Job_id         string `json:"job_id"`
	Result         any    `json:"result"`
	Status         string `json:"status"`
	Units_label    string `json:"units_label"`
	Updated_at     string `json:"updated_at"`
}

// ListKeysResponseItemsItem is one row of ListKeys's "items" list.
type ListKeysResponseItemsItem struct {
	Created_at   string `json:"created_at"`
	Expires_at   string `json:"expires_at"`
	Id           string `json:"id"`
	Last_used_at string `json:"last_used_at"`
	Name         string `json:"name"`
	Prefix       string `json:"prefix"`
}

// ListKeysResponse is returned by ListKeys.
type ListKeysResponse struct {
	Items []ListKeysResponseItemsItem `json:"items"`
	Total int64                       `json:"total"`
}

// RotateKeyResponse is returned by RotateKey.
type RotateKeyResponse struct {
	Key string `json:"key"`
}

// GetUsageResponse is returned by GetUsage.
type GetUsageResponse struct {
	Breakdown    []any  `json:"breakdown"`
	Cap          int64  `json:"cap"`
	Period_end   string `json:"period_end"`
	Period_start string `json:"period_start"`
	Plan_id      string `json:"plan_id"`
	Remaining    int64  `json:"remaining"`
	Total_calls  int64  `json:"total_calls"`
	Total_units  int64  `json:"total_units"`
	Used         int64  `json:"used"`
}

// ListUsageEventsResponseDataItem is one row of ListUsageEvents's "data" list.
type ListUsageEventsResponseDataItem struct {
	Billable_units string `json:"billable_units"`
	Created_at     string `json:"created_at"`
	Id             string `json:"id"`
	Operation      string `json:"operation"`
}

// ListUsageEventsResponse is returned by ListUsageEvents.
type ListUsageEventsResponse struct {
	Data     []ListUsageEventsResponseDataItem `json:"data"`
	Has_more bool                              `json:"has_more"`
	Limit    int64                             `json:"limit"`
	Page     int64                             `json:"page"`
}

// ListWebhookDeliveriesResponseItemsItem is one row of ListWebhookDeliveries's "items" list.
type ListWebhookDeliveriesResponseItemsItem struct {
	Attempts           int64  `json:"attempts"`
	Created_at         string `json:"created_at"`
	Endpoint_url       string `json:"endpoint_url"`
	Event_id           string `json:"event_id"`
	Id                 string `json:"id"`
	Last_response_code int64  `json:"last_response_code"`
	Status             string `json:"status"`
}

// ListWebhookDeliveriesResponse is returned by ListWebhookDeliveries.
type ListWebhookDeliveriesResponse struct {
	Items []ListWebhookDeliveriesResponseItemsItem `json:"items"`
	Total int64                                    `json:"total"`
}

// ListWebhookEndpointsResponse is returned by ListWebhookEndpoints.
type ListWebhookEndpointsResponse struct {
	Items []any `json:"items"`
	Total int64 `json:"total"`
}

// CreateWebhookEndpointResponse is returned by CreateWebhookEndpoint.
type CreateWebhookEndpointResponse struct {
	Active            bool   `json:"active"`
	Created_at        string `json:"created_at"`
	Id                string `json:"id"`
	Secret_hex        string `json:"secret_hex"`
	Subscribed_events []any  `json:"subscribed_events"`
	Url               string `json:"url"`
}

// RotateWebhookEndpointSecretResponse is returned by RotateWebhookEndpointSecret.
type RotateWebhookEndpointSecretResponse struct {
	Secret_hex string `json:"secret_hex"`
}

// Healthz calls GET /healthz (healthz).
func (c *Client) Healthz(ctx context.Context) (*HealthzResponse, error) {
	resp, err := c.do(ctx, http.MethodGet, "/healthz", "", nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out HealthzResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// Readyz calls GET /readyz (readyz).
func (c *Client) Readyz(ctx context.Context) (*ReadyzResponse, error) {
	resp, err := c.do(ctx, http.MethodGet, "/readyz", "", nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ReadyzResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// InvokeEcho calls POST /v1/echo (invoke echo).
// apiKey is sent as the X-API-Key header.
func (c *Client) InvokeEcho(ctx context.Context, apiKey string, payload any) (map[string]any, error) {
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("crucible: marshal payload: %w", err)
	}
	resp, err := c.do(ctx, http.MethodPost, "/v1/echo", apiKey, body)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	out := make(map[string]any)
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	if out == nil {
		out = make(map[string]any)
	}
	return out, nil
}

// ListErrors calls GET /v1/errors (list errors).
// apiKey is sent as the X-API-Key header.
func (c *Client) ListErrors(ctx context.Context, apiKey string, from string, to string, operation string, code string, page int64, limit int64) (*ListErrorsResponse, error) {
	q := url.Values{}
	if from != "" {
		q.Set("from", from)
	}
	if to != "" {
		q.Set("to", to)
	}
	if operation != "" {
		q.Set("operation", operation)
	}
	if code != "" {
		q.Set("code", code)
	}
	if page != 0 {
		q.Set("page", strconv.FormatInt(page, 10))
	}
	if limit != 0 {
		q.Set("limit", strconv.FormatInt(limit, 10))
	}
	reqPath := "/v1/errors"
	if len(q) > 0 {
		reqPath += "?" + q.Encode()
	}
	resp, err := c.do(ctx, http.MethodGet, reqPath, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ListErrorsResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// ListJobs calls GET /v1/jobs (list jobs).
// apiKey is sent as the X-API-Key header.
func (c *Client) ListJobs(ctx context.Context, apiKey string, page int64, perPage int64, status string, operation string) (*ListJobsResponse, error) {
	q := url.Values{}
	if page != 0 {
		q.Set("page", strconv.FormatInt(page, 10))
	}
	if perPage != 0 {
		q.Set("per_page", strconv.FormatInt(perPage, 10))
	}
	if status != "" {
		q.Set("status", status)
	}
	if operation != "" {
		q.Set("operation", operation)
	}
	reqPath := "/v1/jobs"
	if len(q) > 0 {
		reqPath += "?" + q.Encode()
	}
	resp, err := c.do(ctx, http.MethodGet, reqPath, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ListJobsResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// GetJob calls GET /v1/jobs/{id} (get job).
// apiKey is sent as the X-API-Key header.
func (c *Client) GetJob(ctx context.Context, apiKey string, id string) (*GetJobResponse, error) {
	path := fmt.Sprintf("/v1/jobs/%s", url.PathEscape(id))
	resp, err := c.do(ctx, http.MethodGet, path, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out GetJobResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// CancelJob calls POST /v1/jobs/{id}/cancel (cancel job).
// apiKey is sent as the X-API-Key header.
func (c *Client) CancelJob(ctx context.Context, apiKey string, id string) (*CancelJobResponse, error) {
	path := fmt.Sprintf("/v1/jobs/%s/cancel", url.PathEscape(id))
	resp, err := c.do(ctx, http.MethodPost, path, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out CancelJobResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// ListKeys calls GET /v1/keys (list keys).
// apiKey is sent as the X-API-Key header.
func (c *Client) ListKeys(ctx context.Context, apiKey string, page int64, perPage int64) (*ListKeysResponse, error) {
	q := url.Values{}
	if page != 0 {
		q.Set("page", strconv.FormatInt(page, 10))
	}
	if perPage != 0 {
		q.Set("per_page", strconv.FormatInt(perPage, 10))
	}
	reqPath := "/v1/keys"
	if len(q) > 0 {
		reqPath += "?" + q.Encode()
	}
	resp, err := c.do(ctx, http.MethodGet, reqPath, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ListKeysResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// RevokeKey calls DELETE /v1/keys/{id} (revoke key).
// apiKey is sent as the X-API-Key header.
func (c *Client) RevokeKey(ctx context.Context, apiKey string, id string) error {
	path := fmt.Sprintf("/v1/keys/%s", url.PathEscape(id))
	resp, err := c.do(ctx, http.MethodDelete, path, apiKey, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return err
	}
	return nil
}

// RotateKey calls POST /v1/keys/{id}/rotate (rotate key).
// apiKey is sent as the X-API-Key header.
func (c *Client) RotateKey(ctx context.Context, apiKey string, id string, payload any) (*RotateKeyResponse, error) {
	if payload == nil {
		payload = map[string]any{}
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("crucible: marshal payload: %w", err)
	}
	path := fmt.Sprintf("/v1/keys/%s/rotate", url.PathEscape(id))
	resp, err := c.do(ctx, http.MethodPost, path, apiKey, body)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out RotateKeyResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// GetUsage calls GET /v1/usage (get usage).
// apiKey is sent as the X-API-Key header.
func (c *Client) GetUsage(ctx context.Context, apiKey string) (*GetUsageResponse, error) {
	resp, err := c.do(ctx, http.MethodGet, "/v1/usage", apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out GetUsageResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// ListUsageEvents calls GET /v1/usage/events (list usage events).
// apiKey is sent as the X-API-Key header.
func (c *Client) ListUsageEvents(ctx context.Context, apiKey string, from string, to string, operation string, page int64, limit int64) (*ListUsageEventsResponse, error) {
	q := url.Values{}
	if from != "" {
		q.Set("from", from)
	}
	if to != "" {
		q.Set("to", to)
	}
	if operation != "" {
		q.Set("operation", operation)
	}
	if page != 0 {
		q.Set("page", strconv.FormatInt(page, 10))
	}
	if limit != 0 {
		q.Set("limit", strconv.FormatInt(limit, 10))
	}
	reqPath := "/v1/usage/events"
	if len(q) > 0 {
		reqPath += "?" + q.Encode()
	}
	resp, err := c.do(ctx, http.MethodGet, reqPath, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ListUsageEventsResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// ListWebhookDeliveries calls GET /v1/webhooks/deliveries (list webhook deliveries).
// apiKey is sent as the X-API-Key header.
func (c *Client) ListWebhookDeliveries(ctx context.Context, apiKey string, page int64, perPage int64) (*ListWebhookDeliveriesResponse, error) {
	q := url.Values{}
	if page != 0 {
		q.Set("page", strconv.FormatInt(page, 10))
	}
	if perPage != 0 {
		q.Set("per_page", strconv.FormatInt(perPage, 10))
	}
	reqPath := "/v1/webhooks/deliveries"
	if len(q) > 0 {
		reqPath += "?" + q.Encode()
	}
	resp, err := c.do(ctx, http.MethodGet, reqPath, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ListWebhookDeliveriesResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// ListWebhookEndpoints calls GET /v1/webhooks/endpoints (list webhook endpoints).
// apiKey is sent as the X-API-Key header.
func (c *Client) ListWebhookEndpoints(ctx context.Context, apiKey string, page int64, perPage int64) (*ListWebhookEndpointsResponse, error) {
	q := url.Values{}
	if page != 0 {
		q.Set("page", strconv.FormatInt(page, 10))
	}
	if perPage != 0 {
		q.Set("per_page", strconv.FormatInt(perPage, 10))
	}
	reqPath := "/v1/webhooks/endpoints"
	if len(q) > 0 {
		reqPath += "?" + q.Encode()
	}
	resp, err := c.do(ctx, http.MethodGet, reqPath, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ListWebhookEndpointsResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// CreateWebhookEndpoint calls POST /v1/webhooks/endpoints (create webhook endpoint).
// apiKey is sent as the X-API-Key header.
func (c *Client) CreateWebhookEndpoint(ctx context.Context, apiKey string, payload any) (*CreateWebhookEndpointResponse, error) {
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("crucible: marshal payload: %w", err)
	}
	resp, err := c.do(ctx, http.MethodPost, "/v1/webhooks/endpoints", apiKey, body)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out CreateWebhookEndpointResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

// DeleteWebhookEndpoint calls DELETE /v1/webhooks/endpoints/{id} (delete webhook endpoint).
// apiKey is sent as the X-API-Key header.
func (c *Client) DeleteWebhookEndpoint(ctx context.Context, apiKey string, id string) error {
	path := fmt.Sprintf("/v1/webhooks/endpoints/%s", url.PathEscape(id))
	resp, err := c.do(ctx, http.MethodDelete, path, apiKey, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return err
	}
	return nil
}

// UpdateWebhookEndpointSubscription calls PATCH /v1/webhooks/endpoints/{id} (update webhook endpoint subscription).
// apiKey is sent as the X-API-Key header.
func (c *Client) UpdateWebhookEndpointSubscription(ctx context.Context, apiKey string, id string, payload any) error {
	if payload == nil {
		payload = map[string]any{}
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("crucible: marshal payload: %w", err)
	}
	path := fmt.Sprintf("/v1/webhooks/endpoints/%s", url.PathEscape(id))
	resp, err := c.do(ctx, http.MethodPatch, path, apiKey, body)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return err
	}
	return nil
}

// RotateWebhookEndpointSecret calls POST /v1/webhooks/endpoints/{id}/rotate-secret (rotate webhook endpoint secret).
// apiKey is sent as the X-API-Key header.
func (c *Client) RotateWebhookEndpointSecret(ctx context.Context, apiKey string, id string) (*RotateWebhookEndpointSecretResponse, error) {
	path := fmt.Sprintf("/v1/webhooks/endpoints/%s/rotate-secret", url.PathEscape(id))
	resp, err := c.do(ctx, http.MethodPost, path, apiKey, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out RotateWebhookEndpointSecretResponse
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	return &out, nil
}

func (c *Client) do(ctx context.Context, method, path, apiKey string, body []byte) (*http.Response, error) {
	// Append path directly: c.baseURL has no trailing slash; path starts with "/".
	// This preserves any base path prefix (e.g. a reverse-proxy subpath).
	reqURL := c.baseURL.String() + path
	var req *http.Request
	var err error
	if body != nil {
		req, err = http.NewRequestWithContext(ctx, method, reqURL, bytes.NewReader(body))
	} else {
		req, err = http.NewRequestWithContext(ctx, method, reqURL, nil)
	}
	if err != nil {
		return nil, fmt.Errorf("crucible: build request: %w", err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if apiKey != "" {
		req.Header.Set("X-API-Key", apiKey)
	}
	req.Header.Set("Accept", "application/json")
	return c.http.Do(req)
}

// checkError returns nil for 2xx responses without touching resp.Body.
// For non-2xx it reads the body (bounded to 64 KiB) to decode the gateway
// error envelope. The caller's defer resp.Body.Close() handles cleanup.
func checkError(resp *http.Response) error {
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		return nil
	}
	var envelope struct {
		Error struct {
			Code      string `json:"code"`
			Message   string `json:"message"`
			Retryable bool   `json:"retryable"`
			RequestID string `json:"request_id"`
		} `json:"error"`
	}
	// Read up to 64 KiB + 1; the extra byte lets us detect oversized bodies explicitly.
	const limit = 64 << 10
	body, readErr := io.ReadAll(io.LimitReader(resp.Body, limit+1))
	if readErr != nil {
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (read body: %v)", resp.StatusCode, readErr)}
	}
	if len(body) > limit {
		// Best-effort bounded drain; connection may not be reusable if body exceeds ~68 KiB.
		_, _ = io.CopyN(io.Discard, resp.Body, 4<<10)
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (error body >%d bytes)", resp.StatusCode, limit)}
	}
	if decErr := json.Unmarshal(body, &envelope); decErr != nil {
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (invalid JSON: %v)", resp.StatusCode, decErr)}
	}
	if envelope.Error.Code == "" {
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (missing error code)", resp.StatusCode)}
	}
	return &APIError{
		Code:      envelope.Error.Code,
		Message:   envelope.Error.Message,
		Retryable: envelope.Error.Retryable,
		RequestID: envelope.Error.RequestID,
	}
}
