// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)

// Package crucible is a type-safe Go client for the Crucible Gateway API.
// Construct a Client with New; all timeouts are the caller's responsibility.
package crucible

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Client calls the Crucible Gateway. Construct with New.
type Client struct {
	baseURL string
	http    *http.Client
}

// New returns a Client targeting baseURL. The caller owns httpClient and is
// responsible for setting timeouts, transport, and TLS configuration.
// baseURL is normalized: query strings, fragments, and credentials are stripped.
// url.Parse is lenient and almost never returns an error for well-formed URLs;
// on the rare parse failure the raw URL is used unchanged.
func New(baseURL string, httpClient *http.Client) *Client {
	u, err := url.Parse(baseURL)
	if err == nil {
		u.RawQuery = ""
		u.Fragment = ""
		u.User = nil
		baseURL = u.String()
	}
	return &Client{baseURL: strings.TrimRight(baseURL, "/"), http: httpClient}
}

// HealthzResponse is returned by Healthz.
type HealthzResponse struct {
	Status string `json:"status"`
}

// ReadyzResponse is returned by Readyz.
type ReadyzResponse struct {
	Checks map[string]string `json:"checks"`
	Status string `json:"status"`
}

// Healthz calls GET /healthz (healthz).
func (c *Client) Healthz(ctx context.Context) (*HealthzResponse, error) {
	resp, err := c.do(ctx, http.MethodGet, "/healthz", "", nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out HealthzResponse
	return &out, json.NewDecoder(resp.Body).Decode(&out)
}

// Readyz calls GET /readyz (readyz).
func (c *Client) Readyz(ctx context.Context) (*ReadyzResponse, error) {
	resp, err := c.do(ctx, http.MethodGet, "/readyz", "", nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ReadyzResponse
	return &out, json.NewDecoder(resp.Body).Decode(&out)
}

// InvokeEcho calls POST /v1/echo (invoke echo).
// apiKey is sent as the X-API-Key header.
func (c *Client) InvokeEcho(ctx context.Context, apiKey string, payload any) (map[string]any, error) {
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("crucible: marshal payload: %w", err)
	}
	resp, err := c.do(ctx, http.MethodPost, "/v1/echo", apiKey, body)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out map[string]any
	err = json.NewDecoder(resp.Body).Decode(&out)
	return out, err
}

func (c *Client) do(ctx context.Context, method, path, apiKey string, body []byte) (*http.Response, error) {
	var req *http.Request
	var err error
	if body != nil {
		req, err = http.NewRequestWithContext(ctx, method, c.baseURL+path, bytes.NewReader(body))
	} else {
		req, err = http.NewRequestWithContext(ctx, method, c.baseURL+path, nil)
	}
	if err != nil {
		return nil, fmt.Errorf("crucible: build request: %w", err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if apiKey != "" {
		req.Header.Set("X-API-Key", apiKey)
	}
	req.Header.Set("Accept", "application/json")
	return c.http.Do(req)
}

// checkError returns nil for 2xx responses without touching resp.Body.
// For non-2xx it reads the body (bounded to 64 KiB) to decode the gateway
// error envelope. The caller's defer resp.Body.Close() handles cleanup.
func checkError(resp *http.Response) error {
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		return nil
	}
	var envelope struct {
		Error struct {
			Code      string `json:"code"`
			Message   string `json:"message"`
			Retryable bool   `json:"retryable"`
		} `json:"error"`
	}
	// Limit to 64 KiB to prevent unbounded reads from malicious servers.
	decErr := json.NewDecoder(io.LimitReader(resp.Body, 64<<10)).Decode(&envelope)
	if decErr != nil || envelope.Error.Code == "" {
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d", resp.StatusCode)}
	}
	return &APIError{
		Code:      envelope.Error.Code,
		Message:   envelope.Error.Message,
		Retryable: envelope.Error.Retryable,
	}
}
