// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)

package crucible_test

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	crucible "github.com/Unluckyathecking/crucible/clients/go"
)

func newClient(t *testing.T, handler http.HandlerFunc) *crucible.Client {
	t.Helper()
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)
	c, err := crucible.New(srv.URL, srv.Client())
	if err != nil {
		t.Fatalf("crucible.New: %v", err)
	}
	return c
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(v); err != nil {
		panic(err)
	}
}

func TestHealthz(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/healthz" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		writeJSON(w, map[string]any{"status": "ok"})
	})
	resp, err := c.Healthz(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if resp.Status != "ok" {
		t.Errorf("Status = %q, want %q", resp.Status, "ok")
	}
}

func TestReadyz(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/readyz" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		writeJSON(w, map[string]any{"checks": map[string]any{"db": "ok"}, "status": "ok"})
	})
	resp, err := c.Readyz(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if resp.Status != "ok" {
		t.Errorf("Status = %q, want %q", resp.Status, "ok")
	}
}

func TestInvokeEcho(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/v1/echo" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		var reqBody map[string]any
		if err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		if reqBody["x"] == nil {
			t.Error("expected request body to contain key x")
		}
		writeJSON(w, map[string]any{"result": "ok"})
	})
	got, err := c.InvokeEcho(context.Background(), "test-key", map[string]any{"x": 1})
	if err != nil {
		t.Fatal(err)
	}
	if got == nil {
		t.Fatal("expected non-nil map, got nil")
	}
	if got["result"] != "ok" {
		t.Errorf("result = %v, want \"ok\"", got["result"])
	}
}

func TestListErrors(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/v1/errors" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"data": []any{}, "has_more": true, "limit": 1, "page": 1})
	})
	_, err := c.ListErrors(context.Background(), "test-key", "", "", "", "", 0, 0)
	if err != nil {
		t.Fatal(err)
	}
}

func TestListJobs(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/v1/jobs" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"items": []any{}, "total": 1})
	})
	_, err := c.ListJobs(context.Background(), "test-key", 0, 0, "", "")
	if err != nil {
		t.Fatal(err)
	}
}

func TestGetJob(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/v1/jobs/test-id" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"billable_units": 1, "created_at": "ok", "error": map[string]any{"db": "ok"}, "job_id": "ok", "result": map[string]any{"db": "ok"}, "status": "ok", "units_label": "ok", "updated_at": "ok"})
	})
	resp, err := c.GetJob(context.Background(), "test-key", "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Created_at != "ok" {
		t.Errorf("Created_at = %q, want %q", resp.Created_at, "ok")
	}
}

func TestCancelJob(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/v1/jobs/test-id/cancel" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"billable_units": 1, "created_at": "ok", "error": map[string]any{"db": "ok"}, "job_id": "ok", "result": map[string]any{"db": "ok"}, "status": "ok", "units_label": "ok", "updated_at": "ok"})
	})
	resp, err := c.CancelJob(context.Background(), "test-key", "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Created_at != "ok" {
		t.Errorf("Created_at = %q, want %q", resp.Created_at, "ok")
	}
}

func TestListKeys(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/v1/keys" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"items": []any{}, "total": 1})
	})
	_, err := c.ListKeys(context.Background(), "test-key", 0, 0)
	if err != nil {
		t.Fatal(err)
	}
}

func TestRevokeKey(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete || r.URL.Path != "/v1/keys/test-id" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		w.WriteHeader(http.StatusNoContent)
	})
	err := c.RevokeKey(context.Background(), "test-key", "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestRotateKey(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/v1/keys/test-id/rotate" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		var reqBody map[string]any
		if err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		if reqBody["x"] == nil {
			t.Error("expected request body to contain key x")
		}
		writeJSON(w, map[string]any{"key": "ok"})
	})
	resp, err := c.RotateKey(context.Background(), "test-key", "test-id", map[string]any{"x": 1})
	if err != nil {
		t.Fatal(err)
	}
	if resp.Key != "ok" {
		t.Errorf("Key = %q, want %q", resp.Key, "ok")
	}
}

func TestGetUsage(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/v1/usage" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"breakdown": []any{}, "cap": 1, "period_end": "ok", "period_start": "ok", "plan_id": "ok", "remaining": 1, "total_calls": 1, "total_units": 1, "used": 1})
	})
	resp, err := c.GetUsage(context.Background(), "test-key")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Period_end != "ok" {
		t.Errorf("Period_end = %q, want %q", resp.Period_end, "ok")
	}
}

func TestListUsageEvents(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/v1/usage/events" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"data": []any{}, "has_more": true, "limit": 1, "page": 1})
	})
	_, err := c.ListUsageEvents(context.Background(), "test-key", "", "", "", 0, 0)
	if err != nil {
		t.Fatal(err)
	}
}

func TestListWebhookDeliveries(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/v1/webhooks/deliveries" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"items": []any{}, "total": 1})
	})
	_, err := c.ListWebhookDeliveries(context.Background(), "test-key", 0, 0)
	if err != nil {
		t.Fatal(err)
	}
}

func TestListWebhookEndpoints(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/v1/webhooks/endpoints" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"items": []any{}, "total": 1})
	})
	_, err := c.ListWebhookEndpoints(context.Background(), "test-key", 0, 0)
	if err != nil {
		t.Fatal(err)
	}
}

func TestCreateWebhookEndpoint(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/v1/webhooks/endpoints" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		var reqBody map[string]any
		if err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		if reqBody["x"] == nil {
			t.Error("expected request body to contain key x")
		}
		writeJSON(w, map[string]any{"active": true, "created_at": "ok", "id": "ok", "secret_hex": "ok", "subscribed_events": []any{}, "url": "ok"})
	})
	resp, err := c.CreateWebhookEndpoint(context.Background(), "test-key", map[string]any{"x": 1})
	if err != nil {
		t.Fatal(err)
	}
	if resp.Created_at != "ok" {
		t.Errorf("Created_at = %q, want %q", resp.Created_at, "ok")
	}
}

func TestDeleteWebhookEndpoint(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete || r.URL.Path != "/v1/webhooks/endpoints/test-id" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		w.WriteHeader(http.StatusNoContent)
	})
	err := c.DeleteWebhookEndpoint(context.Background(), "test-key", "test-id")
	if err != nil {
		t.Fatal(err)
	}
}

func TestUpdateWebhookEndpointSubscription(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPatch || r.URL.Path != "/v1/webhooks/endpoints/test-id" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		var reqBody map[string]any
		if err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		if reqBody["x"] == nil {
			t.Error("expected request body to contain key x")
		}
		w.WriteHeader(http.StatusNoContent)
	})
	err := c.UpdateWebhookEndpointSubscription(context.Background(), "test-key", "test-id", map[string]any{"x": 1})
	if err != nil {
		t.Fatal(err)
	}
}

func TestRotateWebhookEndpointSecret(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/v1/webhooks/endpoints/test-id/rotate-secret" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		writeJSON(w, map[string]any{"secret_hex": "ok"})
	})
	resp, err := c.RotateWebhookEndpointSecret(context.Background(), "test-key", "test-id")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Secret_hex != "ok" {
		t.Errorf("Secret_hex = %q, want %q", resp.Secret_hex, "ok")
	}
}

func TestInvokeEcho_nullBody(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte("null"))
	})
	got, err := c.InvokeEcho(context.Background(), "test-key", map[string]any{"x": 1})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got == nil {
		t.Error("expected non-nil map for null JSON body, got nil")
	}
	if len(got) != 0 {
		t.Errorf("expected empty map, got %v", got)
	}
}

func TestListErrors_queryEncoding(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if got := r.URL.Query().Get("from"); got != "v" {
			t.Errorf("query from = %q, want %q", got, "v")
		}
		if got := r.URL.Query().Get("to"); got != "v" {
			t.Errorf("query to = %q, want %q", got, "v")
		}
		if got := r.URL.Query().Get("operation"); got != "v" {
			t.Errorf("query operation = %q, want %q", got, "v")
		}
		if got := r.URL.Query().Get("code"); got != "v" {
			t.Errorf("query code = %q, want %q", got, "v")
		}
		if got := r.URL.Query().Get("page"); got != "2" {
			t.Errorf("query page = %q, want %q", got, "2")
		}
		if got := r.URL.Query().Get("limit"); got != "2" {
			t.Errorf("query limit = %q, want %q", got, "2")
		}
		writeJSON(w, map[string]any{})
	})
	_, _ = c.ListErrors(context.Background(), "test-key", "v", "v", "v", "v", 2, 2)
}

func TestRotateKey_defaultsMissingOptionalBody(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if ct := r.Header.Get("Content-Type"); ct != "application/json" {
			t.Errorf("Content-Type = %q, want application/json (a body must still be sent)", ct)
		}
		var reqBody map[string]any
		if err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		if len(reqBody) != 0 {
			t.Errorf("request body = %v, want {}", reqBody)
		}
		writeJSON(w, map[string]any{})
	})
	_, err := c.RotateKey(context.Background(), "test-key", "test-id", nil)
	if err != nil {
		t.Fatal(err)
	}
}

func TestAPIError_typed(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusUnauthorized)
		writeJSON(w, map[string]any{
			"error": map[string]any{
				"code":      "UNAUTHORIZED",
				"message":   "invalid API key",
				"retryable": false,
			},
		})
	})
	_, err := c.InvokeEcho(context.Background(), "bad-key", map[string]any{})
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	var apiErr *crucible.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("expected *crucible.APIError, got %T: %v", err, err)
	}
	if apiErr.Code != "UNAUTHORIZED" {
		t.Errorf("Code = %q, want %q", apiErr.Code, "UNAUTHORIZED")
	}
	if apiErr.Retryable {
		t.Error("Retryable should be false")
	}
}

func TestAPIError_retryable(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusTooManyRequests)
		writeJSON(w, map[string]any{
			"error": map[string]any{
				"code":      "RATE_LIMITED",
				"message":   "slow down",
				"retryable": true,
			},
		})
	})
	_, err := c.InvokeEcho(context.Background(), "key", map[string]any{})
	var apiErr *crucible.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("expected *crucible.APIError, got %T", err)
	}
	if !apiErr.Retryable {
		t.Error("Retryable should be true")
	}
}

func TestAPIError_unknownBody(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte("not json"))
	})
	_, err := c.InvokeEcho(context.Background(), "bad-key", map[string]any{})
	var apiErr *crucible.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("expected *crucible.APIError, got %T", err)
	}
	if apiErr.Code != "UNKNOWN" {
		t.Errorf("Code = %q, want %q", apiErr.Code, "UNKNOWN")
	}
}
