// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)

package crucible_test

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	crucible "github.com/Unluckyathecking/crucible/clients/go"
)

func newClient(t *testing.T, handler http.HandlerFunc) *crucible.Client {
	t.Helper()
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)
	c, err := crucible.New(srv.URL, srv.Client())
	if err != nil {
		t.Fatalf("crucible.New: %v", err)
	}
	return c
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(v); err != nil {
		panic(err)
	}
}

func TestHealthz(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/healthz" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		writeJSON(w, map[string]any{"status": "ok"})
	})
	resp, err := c.Healthz(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if resp.Status != "ok" {
		t.Errorf("Status = %q, want %q", resp.Status, "ok")
	}
}

func TestReadyz(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/readyz" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		writeJSON(w, map[string]any{"checks": map[string]any{"db": "ok"}, "status": "ok"})
	})
	resp, err := c.Readyz(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if resp.Status != "ok" {
		t.Errorf("Status = %q, want %q", resp.Status, "ok")
	}
}

func TestInvokeEcho(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/v1/echo" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		}
		if got := r.Header.Get("X-API-Key"); got == "" {
			t.Error("X-API-Key header missing")
		}
		var reqBody map[string]any
		if err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		if reqBody["x"] == nil {
			t.Error("expected request body to contain key x")
		}
		writeJSON(w, map[string]any{"result": "ok"})
	})
	got, err := c.InvokeEcho(context.Background(), "test-key", map[string]any{"x": 1})
	if err != nil {
		t.Fatal(err)
	}
	if got == nil {
		t.Fatal("expected non-nil map, got nil")
	}
	if got["result"] != "ok" {
		t.Errorf("result = %v, want \"ok\"", got["result"])
	}
}

func TestInvokeEcho_nullBody(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte("null"))
	})
	got, err := c.InvokeEcho(context.Background(), "test-key", map[string]any{"x": 1})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got == nil {
		t.Error("expected non-nil map for null JSON body, got nil")
	}
	if len(got) != 0 {
		t.Errorf("expected empty map, got %v", got)
	}
}

func TestAPIError_typed(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusUnauthorized)
		writeJSON(w, map[string]any{
			"error": map[string]any{
				"code":      "UNAUTHORIZED",
				"message":   "invalid API key",
				"retryable": false,
			},
		})
	})
	_, err := c.InvokeEcho(context.Background(), "bad-key", map[string]any{})
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	var apiErr *crucible.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("expected *crucible.APIError, got %T: %v", err, err)
	}
	if apiErr.Code != "UNAUTHORIZED" {
		t.Errorf("Code = %q, want %q", apiErr.Code, "UNAUTHORIZED")
	}
	if apiErr.Retryable {
		t.Error("Retryable should be false")
	}
}

func TestAPIError_retryable(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusTooManyRequests)
		writeJSON(w, map[string]any{
			"error": map[string]any{
				"code":      "RATE_LIMITED",
				"message":   "slow down",
				"retryable": true,
			},
		})
	})
	_, err := c.InvokeEcho(context.Background(), "key", map[string]any{})
	var apiErr *crucible.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("expected *crucible.APIError, got %T", err)
	}
	if !apiErr.Retryable {
		t.Error("Retryable should be true")
	}
}

func TestAPIError_unknownBody(t *testing.T) {
	c := newClient(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte("not json"))
	})
	_, err := c.InvokeEcho(context.Background(), "bad-key", map[string]any{})
	var apiErr *crucible.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("expected *crucible.APIError, got %T", err)
	}
	if apiErr.Code != "UNKNOWN" {
		t.Errorf("Code = %q, want %q", apiErr.Code, "UNKNOWN")
	}
}
