// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)

// Package crucible is a type-safe Go client for the Crucible Gateway API.
// Construct a Client with New; all timeouts are the caller's responsibility.
package crucible

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Client calls the Crucible Gateway. Construct with New.
type Client struct {
	baseURL *url.URL
	http    *http.Client
}

// New returns a Client targeting baseURL, or an error if baseURL cannot be parsed.
// httpClient defaults to http.DefaultClient when nil. Note: http.DefaultClient has no
// timeout; callers must supply a client with Timeout set or use context.WithTimeout.
// baseURL is normalized: query strings, fragments, and credentials are stripped; trailing
// slashes on the path are removed so that appending spec paths (which start with "/") is correct.
// Any base path prefix (e.g. "/crucible" for a reverse-proxy subpath) is preserved.
func New(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("crucible: invalid baseURL %q: %w", baseURL, err)
	}
	u.RawQuery = ""
	u.Fragment = ""
	u.User = nil
	u.Path = strings.TrimRight(u.Path, "/")
	return &Client{baseURL: u, http: httpClient}, nil
}

// HealthzResponse is returned by Healthz.
type HealthzResponse struct {
	Status string `json:"status"`
}

// ReadyzResponse is returned by Readyz.
type ReadyzResponse struct {
	Checks map[string]string `json:"checks"`
	Status string `json:"status"`
}

// Healthz calls GET /healthz (healthz).
func (c *Client) Healthz(ctx context.Context) (*HealthzResponse, error) {
	resp, err := c.do(ctx, http.MethodGet, "/healthz", "", nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out HealthzResponse
	return &out, json.NewDecoder(resp.Body).Decode(&out)
}

// Readyz calls GET /readyz (readyz).
func (c *Client) Readyz(ctx context.Context) (*ReadyzResponse, error) {
	resp, err := c.do(ctx, http.MethodGet, "/readyz", "", nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	var out ReadyzResponse
	return &out, json.NewDecoder(resp.Body).Decode(&out)
}

// InvokeEcho calls POST /v1/echo (invoke echo).
// apiKey is sent as the X-API-Key header.
func (c *Client) InvokeEcho(ctx context.Context, apiKey string, payload any) (map[string]any, error) {
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("crucible: marshal payload: %w", err)
	}
	resp, err := c.do(ctx, http.MethodPost, "/v1/echo", apiKey, body)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if err := checkError(resp); err != nil {
		return nil, err
	}
	out := make(map[string]any)
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		return nil, fmt.Errorf("crucible: decode response: %w", decErr)
	}
	if out == nil {
		out = make(map[string]any)
	}
	return out, nil
}

func (c *Client) do(ctx context.Context, method, path, apiKey string, body []byte) (*http.Response, error) {
	// Append path directly: c.baseURL has no trailing slash; path starts with "/".
	// This preserves any base path prefix (e.g. a reverse-proxy subpath).
	reqURL := c.baseURL.String() + path
	var req *http.Request
	var err error
	if body != nil {
		req, err = http.NewRequestWithContext(ctx, method, reqURL, bytes.NewReader(body))
	} else {
		req, err = http.NewRequestWithContext(ctx, method, reqURL, nil)
	}
	if err != nil {
		return nil, fmt.Errorf("crucible: build request: %w", err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if apiKey != "" {
		req.Header.Set("X-API-Key", apiKey)
	}
	req.Header.Set("Accept", "application/json")
	return c.http.Do(req)
}

// checkError returns nil for 2xx responses without touching resp.Body.
// For non-2xx it reads the body (bounded to 64 KiB) to decode the gateway
// error envelope. The caller's defer resp.Body.Close() handles cleanup.
func checkError(resp *http.Response) error {
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		return nil
	}
	var envelope struct {
		Error struct {
			Code      string `json:"code"`
			Message   string `json:"message"`
			Retryable bool   `json:"retryable"`
		} `json:"error"`
	}
	// Read up to 64 KiB + 1; the extra byte lets us detect oversized bodies explicitly.
	const limit = 64 << 10
	body, readErr := io.ReadAll(io.LimitReader(resp.Body, limit+1))
	if readErr != nil {
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (read body: %v)", resp.StatusCode, readErr)}
	}
	if len(body) > limit {
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (error body >%d bytes)", resp.StatusCode, limit)}
	}
	if decErr := json.Unmarshal(body, &envelope); decErr != nil {
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (invalid JSON: %v)", resp.StatusCode, decErr)}
	}
	if envelope.Error.Code == "" {
		return &APIError{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (missing error code)", resp.StatusCode)}
	}
	return &APIError{
		Code:      envelope.Error.Code,
		Message:   envelope.Error.Message,
		Retryable: envelope.Error.Retryable,
	}
}
