// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)

package crucible

import "fmt"

// APIError is returned when the gateway responds with a non-2xx status.
// It models the error envelope: {"error":{"code":"...","message":"...","retryable":true}}.
type APIError struct {
	Code      string
	Message   string
	Retryable bool
}

func (e *APIError) Error() string {
	return fmt.Sprintf("crucible: %s: %s (retryable=%v)", e.Code, e.Message, e.Retryable)
}
