"""Code generated by scripts/gen-clients.sh — DO NOT EDIT.
Source: clients/openapi.json (Crucible Gateway 1.0.0)
"""

from __future__ import annotations


class ApiError(Exception):
    """Raised when the gateway responds with a non-2xx status.

    Models the error envelope:
    {"error":{"code":"...","message":"...","retryable":true,"request_id":"..."}}.
    """

    def __init__(
        self,
        code: str,
        message: str,
        retryable: bool = False,
        request_id: str = "",
        status: int = 0,
    ) -> None:
        super().__init__(
            f"crucible: {code}: {message} (retryable={retryable}, request_id={request_id})"
        )
        self.code = code
        self.message = message
        self.retryable = retryable
        self.request_id = request_id
        self.status = status
