"""Code generated by scripts/gen-clients.sh — DO NOT EDIT.
Source: clients/openapi.json (test harness for the generated client)
"""
from __future__ import annotations

import contextlib
import http.server
import json
import threading
import time
import urllib.error
from dataclasses import dataclass
from typing import Any, Callable, Dict, Optional
from unittest.mock import patch
from urllib.parse import parse_qs, urlparse

from crucible_client import ApiError, Client


class CaseInsensitiveHeaders(Dict[str, str]):
    """Plain dict subclass with case-insensitive .get()/__getitem__/__contains__.

    HTTP header names are case-insensitive (RFC 7230 §3.2); urllib.request
    normalizes the casing it sends on the wire (e.g. "X-API-Key" becomes
    "X-Api-Key"), so a plain dict keyed by the header name as received would
    make lookups depend on urllib's internal capitalization behavior.
    """

    def get(self, key: str, default: Any = None) -> Any:
        key_lower = key.lower()
        for k, v in self.items():
            if k.lower() == key_lower:
                return v
        return default


@dataclass
class CapturedRequest:
    method: str
    path: str
    headers: CaseInsensitiveHeaders
    body: bytes


@dataclass
class StubResponse:
    status: int
    body: Optional[bytes] = None
    content_type: str = "application/json"


@contextlib.contextmanager
def serve(handler: Callable[[CapturedRequest], StubResponse]):
    captured: Dict[str, CapturedRequest] = {}

    class _Handler(http.server.BaseHTTPRequestHandler):
        def _handle(self) -> None:
            length = int(self.headers.get("Content-Length", 0) or 0)
            body = self.rfile.read(length) if length else b""
            req = CapturedRequest(
                method=self.command,
                path=self.path,
                headers=CaseInsensitiveHeaders(self.headers.items()),
                body=body,
            )
            captured["last"] = req
            resp = handler(req)
            self.send_response(resp.status)
            if resp.body is not None:
                self.send_header("Content-Type", resp.content_type)
                self.send_header("Content-Length", str(len(resp.body)))
            self.end_headers()
            if resp.body is not None:
                self.wfile.write(resp.body)

        def do_GET(self) -> None:
            self._handle()

        def do_POST(self) -> None:
            self._handle()

        def do_DELETE(self) -> None:
            self._handle()

        def do_PATCH(self) -> None:
            self._handle()

        def log_message(self, *args: Any) -> None:
            pass

    server = http.server.HTTPServer(("127.0.0.1", 0), _Handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"http://127.0.0.1:{server.server_port}", captured
    finally:
        server.shutdown()
        thread.join()


def json_response(status: int, payload: Any) -> StubResponse:
    return StubResponse(status=status, body=json.dumps(payload).encode("utf-8"))


def query_params(path: str) -> Dict[str, list]:
    return parse_qs(urlparse(path).query)



def test_healthz():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/healthz"
        return json_response(200, {"status": "ok"})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.healthz()
        assert got is not None


def test_readyz():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/readyz"
        return json_response(200, {"checks": {"db": "ok"}, "status": "ok"})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.readyz()
        assert got is not None


def test_invoke_echo():
    def handler(req):
        assert req.method == "POST"
        assert req.path.split("?")[0] == "/v1/echo"
        assert req.headers.get("X-API-Key") == "test-key"
        req_body = json.loads(req.body)
        assert req_body.get("x") == 1
        return json_response(200, {"result": "ok"})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.invoke_echo(payload={"x": 1}, api_key="test-key")
        assert got is not None


def test_list_errors():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/v1/errors"
        assert req.headers.get("X-API-Key") == "test-key"
        return json_response(200, {"data": [], "has_more": True, "limit": 1, "page": 1})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.list_errors(from_="v", to="v", operation="v", code="v", page=2, limit=2, api_key="test-key")
        assert got is not None


def test_list_jobs():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/v1/jobs"
        assert req.headers.get("X-API-Key") == "test-key"
        return json_response(200, {"items": [], "total": 1})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.list_jobs(page=2, per_page=2, status="v", operation="v", api_key="test-key")
        assert got is not None


def test_get_job():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/v1/jobs/test-id"
        assert req.headers.get("X-API-Key") == "test-key"
        return json_response(200, {"billable_units": 1, "created_at": "ok", "error": {"db": "ok"}, "job_id": "ok", "result": {"db": "ok"}, "status": "ok", "units_label": "ok", "updated_at": "ok"})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.get_job("test-id", api_key="test-key")
        assert got is not None


def test_list_keys():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/v1/keys"
        assert req.headers.get("X-API-Key") == "test-key"
        return json_response(200, {"items": [], "total": 1})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.list_keys(page=2, per_page=2, api_key="test-key")
        assert got is not None


def test_revoke_key():
    def handler(req):
        assert req.method == "DELETE"
        assert req.path.split("?")[0] == "/v1/keys/test-id"
        assert req.headers.get("X-API-Key") == "test-key"
        return StubResponse(status=204)

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        result = c.revoke_key("test-id", api_key="test-key")
        assert result is None


def test_rotate_key():
    def handler(req):
        assert req.method == "POST"
        assert req.path.split("?")[0] == "/v1/keys/test-id/rotate"
        assert req.headers.get("X-API-Key") == "test-key"
        req_body = json.loads(req.body)
        assert req_body.get("x") == 1
        return json_response(200, {"key": "ok"})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.rotate_key("test-id", payload={"x": 1}, api_key="test-key")
        assert got is not None


def test_get_usage():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/v1/usage"
        assert req.headers.get("X-API-Key") == "test-key"
        return json_response(200, {"breakdown": [], "cap": 1, "period_end": "ok", "period_start": "ok", "plan_id": "ok", "remaining": 1, "total_calls": 1, "total_units": 1, "used": 1})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.get_usage(api_key="test-key")
        assert got is not None


def test_list_usage_events():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/v1/usage/events"
        assert req.headers.get("X-API-Key") == "test-key"
        return json_response(200, {"data": [], "has_more": True, "limit": 1, "page": 1})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.list_usage_events(from_="v", to="v", operation="v", page=2, limit=2, api_key="test-key")
        assert got is not None


def test_list_webhook_endpoints():
    def handler(req):
        assert req.method == "GET"
        assert req.path.split("?")[0] == "/v1/webhooks/endpoints"
        assert req.headers.get("X-API-Key") == "test-key"
        return json_response(200, {"items": [], "total": 1})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.list_webhook_endpoints(page=2, per_page=2, api_key="test-key")
        assert got is not None


def test_create_webhook_endpoint():
    def handler(req):
        assert req.method == "POST"
        assert req.path.split("?")[0] == "/v1/webhooks/endpoints"
        assert req.headers.get("X-API-Key") == "test-key"
        req_body = json.loads(req.body)
        assert req_body.get("x") == 1
        return json_response(200, {"active": True, "created_at": "ok", "id": "ok", "secret_hex": "ok", "subscribed_events": [], "url": "ok"})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.create_webhook_endpoint(payload={"x": 1}, api_key="test-key")
        assert got is not None


def test_delete_webhook_endpoint():
    def handler(req):
        assert req.method == "DELETE"
        assert req.path.split("?")[0] == "/v1/webhooks/endpoints/test-id"
        assert req.headers.get("X-API-Key") == "test-key"
        return StubResponse(status=204)

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        result = c.delete_webhook_endpoint("test-id", api_key="test-key")
        assert result is None


def test_update_webhook_endpoint_subscription():
    def handler(req):
        assert req.method == "PATCH"
        assert req.path.split("?")[0] == "/v1/webhooks/endpoints/test-id"
        assert req.headers.get("X-API-Key") == "test-key"
        req_body = json.loads(req.body)
        assert req_body.get("x") == 1
        return StubResponse(status=204)

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        result = c.update_webhook_endpoint_subscription("test-id", payload={"x": 1}, api_key="test-key")
        assert result is None


def test_rotate_webhook_endpoint_secret():
    def handler(req):
        assert req.method == "POST"
        assert req.path.split("?")[0] == "/v1/webhooks/endpoints/test-id/rotate-secret"
        assert req.headers.get("X-API-Key") == "test-key"
        return json_response(200, {"secret_hex": "ok"})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.rotate_webhook_endpoint_secret("test-id", api_key="test-key")
        assert got is not None


def test_invoke_echo_null_body():
    def handler(req):
        return StubResponse(status=200, body=b"null", content_type="application/json")

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.invoke_echo(payload={"x": 1}, api_key="test-key")
        assert got == {}


def test_list_errors_query_encoding():
    def handler(req):
        return json_response(200, {})

    with serve(handler) as (base_url, captured):
        c = Client(base_url)
        c.list_errors(from_="v", to="v", operation="v", code="v", page=2, limit=2, api_key="test-key")
    assert query_params(captured["last"].path).get("from") == ["v"]
    assert query_params(captured["last"].path).get("to") == ["v"]
    assert query_params(captured["last"].path).get("operation") == ["v"]
    assert query_params(captured["last"].path).get("code") == ["v"]
    assert query_params(captured["last"].path).get("page") == ["2"]
    assert query_params(captured["last"].path).get("limit") == ["2"]


def test_rotate_key_defaults_missing_optional_body():
    def handler(req):
        assert req.headers.get("Content-Type") == "application/json"
        assert json.loads(req.body) == {}
        return json_response(200, {})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        got = c.rotate_key("test-id", api_key="test-key")


def test_api_error_typed():
    def handler(req):
        return json_response(401, {"error": {"code": "UNAUTHORIZED", "message": "invalid API key", "retryable": False, "request_id": "req-123"}})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        try:
            c.invoke_echo(payload={"x": 1}, api_key="bad-key")
            assert False, "expected ApiError"
        except ApiError as e:
            assert e.code == "UNAUTHORIZED"
            assert e.retryable is False
            assert e.request_id == "req-123"


def test_api_error_retryable():
    def handler(req):
        return json_response(429, {"error": {"code": "RATE_LIMITED", "message": "slow down", "retryable": True}})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        try:
            c.invoke_echo(payload={"x": 1}, api_key="key")
            assert False, "expected ApiError"
        except ApiError as e:
            assert e.retryable is True


def test_api_error_unknown_body():
    def handler(req):
        return StubResponse(status=500, body=b"not json", content_type="text/plain")

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        try:
            c.invoke_echo(payload={"x": 1}, api_key="bad-key")
            assert False, "expected ApiError"
        except ApiError as e:
            assert e.code == "UNKNOWN"


def test_healthz_unexpected_204_raises():
    def handler(req):
        return StubResponse(status=204)

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        try:
            c.healthz()
            assert False, "expected ApiError"
        except ApiError as e:
            assert e.code == "UNKNOWN"


def test_healthz_non_utf8_error_body():
    def handler(req):
        return StubResponse(status=500, body=b"\xff\xfe not valid utf8 \x80\x81", content_type="application/json")

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        try:
            c.healthz()
            assert False, "expected ApiError"
        except ApiError as e:
            assert e.code == "UNKNOWN"


def test_invoke_echo_rejects_non_finite_payload():
    def handler(req):
        return json_response(200, {})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url)
        try:
            c.invoke_echo(payload={"x": float("nan")}, api_key="test-key")
            assert False, "expected ValueError"
        except ValueError:
            pass


def test_client_stores_timeout():
    c = Client("http://example.invalid", timeout=2.5)
    assert c.timeout == 2.5


def test_healthz_respects_timeout():
    def handler(req):
        time.sleep(0.3)
        return json_response(200, {})

    with serve(handler) as (base_url, _captured):
        c = Client(base_url, timeout=0.05)
        try:
            c.healthz()
            assert False, "expected a timeout error"
        except ApiError as e:
            assert e.code == "UNKNOWN"


def test_healthz_wrapped_connect_timeout_is_retryable():
    def raise_wrapped_timeout(*args, **kwargs):
        raise urllib.error.URLError(TimeoutError("timed out"))

    with patch("urllib.request.urlopen", side_effect=raise_wrapped_timeout):
        c = Client("http://example.invalid")
        try:
            c.healthz()
            assert False, "expected ApiError"
        except ApiError as e:
            assert e.code == "UNKNOWN"
            assert e.retryable is True


def test_client_normalizes_base_url():
    c = Client("https://gw.example:8443/api/?debug=1#frag")
    assert c.base_url == "https://gw.example:8443/api"


def test_client_normalizes_ipv6_base_url():
    c = Client("http://[::1]:8080/api/")
    assert c.base_url == "http://[::1]:8080/api"
