#!/usr/bin/env bash
# gen-clients.sh — regenerate Go and TypeScript consumer client SDKs from
# clients/openapi.json. Idempotent: a second run produces zero git diff.
# Requirements: python3 (stdlib only), go 1.22+.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SPEC="${REPO_ROOT}/clients/openapi.json"

if [[ ! -f "${SPEC}" ]]; then
  echo "error: spec not found at ${SPEC}" >&2
  exit 1
fi

python3 - "${SPEC}" "${REPO_ROOT}" <<'PYEOF'
import json, os, sys

SPEC_PATH = sys.argv[1]
REPO_ROOT  = sys.argv[2]
GO_DIR     = os.path.join(REPO_ROOT, "clients", "go")
TS_DIR     = os.path.join(REPO_ROOT, "clients", "typescript")

with open(SPEC_PATH) as f:
    spec = json.load(f)

info    = spec["info"]
title   = info["title"]
version = info["version"]
header  = (
    f"// Code generated by scripts/gen-clients.sh — DO NOT EDIT.\n"
    f"// Source: clients/openapi.json ({title} {version})\n"
)

# ── API-key header name from securitySchemes ─────────────────────────────────
api_key_header = "X-API-Key"
for scheme in spec.get("components", {}).get("securitySchemes", {}).values():
    if scheme.get("type") == "apiKey" and scheme.get("in") == "header":
        api_key_header = scheme.get("name", api_key_header)
        break

# ── Collect typed operations (skip billing/text-plain) ───────────────────────
class Op:
    def __init__(self, path, method, op):
        self.path     = path
        self.method   = method
        self.op_id    = op["operationId"]
        self.tags     = op.get("tags", [])
        self.secure   = bool(op.get("security"))
        self.has_body = bool(op.get("requestBody"))
        resp200 = op.get("responses", {}).get("200", {})
        self.resp200 = resp200
        self.json_ok = "application/json" in resp200.get("content", {})

ops = []
for path, item in sorted(spec["paths"].items()):
    for method in ("get", "post"):
        if method not in item:
            continue
        op = Op(path, method, item[method])
        if "billing" in op.tags:
            continue
        if not op.json_ok:
            continue
        ops.append(op)

# ── operationId → Go TitleCase / TS camelCase ────────────────────────────────
def go_name(op_id):
    return "".join(p.capitalize() for p in op_id.split("_"))

def ts_name(op_id):
    parts = op_id.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])

# Find first authenticated POST op (used in error test stubs).
first_auth_post = next((op for op in ops if op.secure and op.method == "post"), None)

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Go client
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

write(os.path.join(GO_DIR, "go.mod"), f"""\
{header}
module github.com/Unluckyathecking/crucible/clients/go

go 1.22
""")

# Overrides the repo-root go.work so `cd clients/go && go build ./...` works.
write(os.path.join(GO_DIR, "go.work"), """\
go 1.22

use .
""")

write(os.path.join(GO_DIR, "errors.go"), f"""\
{header}
package crucible

import "fmt"

// APIError is returned when the gateway responds with a non-2xx status.
// It models the error envelope: {{"error":{{"code":"...","message":"...","retryable":true}}}}.
type APIError struct {{
\tCode      string
\tMessage   string
\tRetryable bool
}}

func (e *APIError) Error() string {{
\treturn fmt.Sprintf("crucible: %s: %s", e.Code, e.Message)
}}
""")

# ── Response types ────────────────────────────────────────────────────────────

def go_response_type(op):
    schema = op.resp200.get("content", {}).get("application/json", {}).get("schema", {})
    props  = schema.get("properties", {})
    if props and not schema.get("additionalProperties"):
        return go_name(op.op_id) + "Response"
    return "map[string]any"

def go_response_structs():
    parts = []
    for op in ops:
        rtype = go_response_type(op)
        if rtype == "map[string]any":
            continue
        schema = op.resp200.get("content", {}).get("application/json", {}).get("schema", {})
        props   = schema.get("properties", {})
        fields  = []
        for fname, fschema in sorted(props.items()):
            go_field = fname.capitalize()
            ftype = fschema.get("type", "any")
            add   = fschema.get("additionalProperties")
            if ftype == "string":
                go_type = "string"
            elif ftype == "boolean":
                go_type = "bool"
            elif ftype == "integer":
                go_type = "int64"
            elif ftype == "number":
                go_type = "float64"
            elif ftype == "array":
                go_type = "[]any"
            elif ftype == "object" and add:
                inner    = add.get("type", "any")
                inner_go = {"string": "string", "integer": "int64", "number": "float64", "boolean": "bool"}.get(inner, "any")
                go_type  = f"map[string]{inner_go}"
            else:
                go_type = "any"
            fields.append(f'\t{go_field} {go_type} `json:"{fname}"`')
        field_block = "\n".join(fields)
        parts.append(
            f"// {rtype} is returned by {go_name(op.op_id)}.\n"
            f"type {rtype} struct {{\n{field_block}\n}}"
        )
    return "\n\n".join(parts) + ("\n\n" if parts else "")

def go_method(op):
    fn     = go_name(op.op_id)
    rtype  = go_response_type(op)
    path   = op.path
    method = "http.MethodGet" if op.method == "get" else "http.MethodPost"

    params = ["ctx context.Context"]
    if op.secure:
        params.append("apiKey string")
    if op.has_body:
        params.append("payload any")
    param_str = ", ".join(params)

    nil_ret = "nil, "
    if rtype == "map[string]any":
        ret_sig  = "(map[string]any, error)"
        out_decl = "\tvar out map[string]any"
        # Two-statement form avoids left-to-right evaluation capturing nil before Decode runs.
        out_ret  = "\terr = json.NewDecoder(resp.Body).Decode(&out)\n\treturn out, err"
    else:
        ret_sig  = f"(*{rtype}, error)"
        out_decl = f"\tvar out {rtype}"
        out_ret  = f"\treturn &out, json.NewDecoder(resp.Body).Decode(&out)"

    lines = [f"// {fn} calls {op.method.upper()} {path} ({op.op_id.replace('_', ' ')})."]
    if op.secure:
        lines.append(f"// apiKey is sent as the {api_key_header} header.")
    lines.append(f"func (c *Client) {fn}({param_str}) {ret_sig} {{")
    if op.has_body:
        lines += [
            "\tbody, err := json.Marshal(payload)",
            "\tif err != nil {",
            '\t\treturn nil, fmt.Errorf("crucible: marshal payload: %w", err)',
            "\t}",
        ]
    api_key_arg = "apiKey" if op.secure else '""'
    body_arg    = "body"   if op.has_body else "nil"
    lines += [
        f'\tresp, err := c.do(ctx, {method}, "{path}", {api_key_arg}, {body_arg})',
        "\tif err != nil {",
        f"\t\treturn {nil_ret}err",
        "\t}",
        "\tdefer resp.Body.Close()",
        "\tif err := checkError(resp); err != nil {",
        f"\t\treturn {nil_ret}err",
        "\t}",
        out_decl,
        out_ret,
        "}",
    ]
    return "\n".join(lines)

structs_go = go_response_structs()
methods_go = "\n\n".join(go_method(op) for op in ops)

write(os.path.join(GO_DIR, "client.go"), f"""\
{header}
// Package crucible is a type-safe Go client for the Crucible Gateway API.
// Construct a Client with New; all timeouts are the caller's responsibility.
package crucible

import (
\t"bytes"
\t"context"
\t"encoding/json"
\t"fmt"
\t"io"
\t"net/http"
\t"net/url"
\t"strings"
)

// Client calls the Crucible Gateway. Construct with New.
type Client struct {{
\tbaseURL string
\thttp    *http.Client
}}

// New returns a Client targeting baseURL. The caller owns httpClient and is
// responsible for setting timeouts, transport, and TLS configuration.
// baseURL is normalized: query strings, fragments, and credentials are stripped.
// url.Parse is lenient and almost never returns an error for well-formed URLs;
// on the rare parse failure the raw URL is used unchanged.
func New(baseURL string, httpClient *http.Client) *Client {{
\tu, err := url.Parse(baseURL)
\tif err == nil {{
\t\tu.RawQuery = ""
\t\tu.Fragment = ""
\t\tu.User = nil
\t\tbaseURL = u.String()
\t}}
\treturn &Client{{baseURL: strings.TrimRight(baseURL, "/"), http: httpClient}}
}}

{structs_go}{methods_go}

func (c *Client) do(ctx context.Context, method, path, apiKey string, body []byte) (*http.Response, error) {{
\tvar req *http.Request
\tvar err error
\tif body != nil {{
\t\treq, err = http.NewRequestWithContext(ctx, method, c.baseURL+path, bytes.NewReader(body))
\t}} else {{
\t\treq, err = http.NewRequestWithContext(ctx, method, c.baseURL+path, nil)
\t}}
\tif err != nil {{
\t\treturn nil, fmt.Errorf("crucible: build request: %w", err)
\t}}
\tif body != nil {{
\t\treq.Header.Set("Content-Type", "application/json")
\t}}
\tif apiKey != "" {{
\t\treq.Header.Set("{api_key_header}", apiKey)
\t}}
\treq.Header.Set("Accept", "application/json")
\treturn c.http.Do(req)
}}

// checkError returns nil for 2xx responses without touching resp.Body.
// For non-2xx it reads the body (bounded to 64 KiB) to decode the gateway
// error envelope. The caller's defer resp.Body.Close() handles cleanup.
func checkError(resp *http.Response) error {{
\tif resp.StatusCode >= 200 && resp.StatusCode < 300 {{
\t\treturn nil
\t}}
\tvar envelope struct {{
\t\tError struct {{
\t\t\tCode      string `json:"code"`
\t\t\tMessage   string `json:"message"`
\t\t\tRetryable bool   `json:"retryable"`
\t\t}} `json:"error"`
\t}}
\t// Read up to 64 KiB + 1; the extra byte lets us detect oversized bodies explicitly.
\tconst limit = 64 << 10
\tbody, readErr := io.ReadAll(io.LimitReader(resp.Body, limit+1))
\tif readErr != nil {{
\t\treturn &APIError{{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d", resp.StatusCode)}}
\t}}
\tif len(body) > limit {{
\t\treturn &APIError{{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (error body >%d bytes)", resp.StatusCode, limit)}}
\t}}
\tif decErr := json.Unmarshal(body, &envelope); decErr != nil || envelope.Error.Code == "" {{
\t\treturn &APIError{{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d", resp.StatusCode)}}
\t}}
\treturn &APIError{{
\t\tCode:      envelope.Error.Code,
\t\tMessage:   envelope.Error.Message,
\t\tRetryable: envelope.Error.Retryable,
\t}}
}}
""")

# ── client_test.go ────────────────────────────────────────────────────────────

def go_test_method(op):
    fn    = go_name(op.op_id)
    rtype = go_response_type(op)
    method_const = "http.MethodGet" if op.method == "get" else "http.MethodPost"

    schema = op.resp200.get("content", {}).get("application/json", {}).get("schema", {})
    props  = schema.get("properties", {})

    # Build response JSON for server stub.
    if rtype == "map[string]any":
        resp_json = 'map[string]any{"result": "ok"}'
    else:
        field_parts = []
        for fname in sorted(props.keys()):
            fschema = props[fname]
            if fschema.get("type") == "string":
                field_parts.append(f'"{fname}": "ok"')
            elif fschema.get("type") == "object":
                field_parts.append(f'"{fname}": map[string]any{{"db": "ok"}}')
        resp_json = "map[string]any{" + ", ".join(field_parts) + "}"

    # Build the client call.
    if op.has_body and op.secure:
        call = f'c.{fn}(context.Background(), "test-key", map[string]any{{"x": 1}})'
    elif op.has_body:
        call = f'c.{fn}(context.Background(), map[string]any{{"x": 1}})'
    elif op.secure:
        call = f'c.{fn}(context.Background(), "test-key")'
    else:
        call = f'c.{fn}(context.Background())'

    lines = [
        f"func Test{fn}(t *testing.T) {{",
        f'\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {{',
        f'\t\tif r.Method != {method_const} || r.URL.Path != "{op.path}" {{',
        f'\t\t\tt.Errorf("unexpected request %s %s", r.Method, r.URL.Path)',
        "\t\t}",
    ]
    if op.secure:
        lines += [
            f'\t\tif got := r.Header.Get("{api_key_header}"); got == "" {{',
            f'\t\t\tt.Error("{api_key_header} header missing")',
            "\t\t}",
        ]
    if op.has_body:
        lines += [
            "\t\tvar reqBody map[string]any",
            "\t\tif err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {",
            '\t\t\tt.Fatalf("decode request body: %v", err)',
            "\t\t}",
            '\t\tif reqBody["x"] == nil {',
            '\t\t\tt.Error("expected request body to contain key x")',
            "\t\t}",
        ]
    lines += [
        f"\t\twriteJSON(w, {resp_json})",
        "\t})",
    ]
    if rtype == "map[string]any":
        lines += [
            f"\tgot, err := {call}",
            "\tif err != nil {",
            "\t\tt.Fatal(err)",
            "\t}",
            "\tif got == nil {",
            '\t\tt.Fatal("expected non-nil map, got nil")',
            "\t}",
            '\tif got["result"] != "ok" {',
            '\t\tt.Errorf("result = %v, want \\"ok\\"", got["result"])',
            "\t}",
            "}",
        ]
    else:
        first_str_field = next(
            (fname for fname in sorted(props.keys()) if props[fname].get("type") == "string"),
            None
        )
        if first_str_field:
            go_field = first_str_field.capitalize()
            lines += [
                f"\tresp, err := {call}",
                "\tif err != nil {",
                "\t\tt.Fatal(err)",
                "\t}",
                f'\tif resp.{go_field} != "ok" {{',
                f'\t\tt.Errorf("{go_field} = %q, want %q", resp.{go_field}, "ok")',
                "\t}",
                "}",
            ]
        else:
            lines += [
                f"\t_, err := {call}",
                "\tif err != nil {",
                "\t\tt.Fatal(err)",
                "\t}",
                "}",
            ]
    return "\n".join(lines)

test_methods_go = "\n\n".join(go_test_method(op) for op in ops)

# Error tests use the first authenticated POST operation (dynamically resolved).
if first_auth_post:
    auth_go_fn = go_name(first_auth_post.op_id)
    auth_go_has_body = first_auth_post.has_body
    if auth_go_has_body:
        auth_go_call_bad  = f'c.{auth_go_fn}(context.Background(), "bad-key", map[string]any{{}})'
        auth_go_call_rate = f'c.{auth_go_fn}(context.Background(), "key", map[string]any{{}})'
    else:
        auth_go_call_bad  = f'c.{auth_go_fn}(context.Background(), "bad-key")'
        auth_go_call_rate = f'c.{auth_go_fn}(context.Background(), "key")'
else:
    auth_go_call_bad  = 'c.Healthz(context.Background())'
    auth_go_call_rate = 'c.Healthz(context.Background())'

write(os.path.join(GO_DIR, "client_test.go"), f"""\
{header}
package crucible_test

import (
\t"context"
\t"encoding/json"
\t"errors"
\t"net/http"
\t"net/http/httptest"
\t"testing"

\tcrucible "github.com/Unluckyathecking/crucible/clients/go"
)

func newClient(t *testing.T, handler http.HandlerFunc) *crucible.Client {{
\tt.Helper()
\tsrv := httptest.NewServer(handler)
\tt.Cleanup(srv.Close)
\treturn crucible.New(srv.URL, srv.Client())
}}

func writeJSON(w http.ResponseWriter, v any) {{
\tw.Header().Set("Content-Type", "application/json")
\tif err := json.NewEncoder(w).Encode(v); err != nil {{
\t\tpanic(err)
\t}}
}}

{test_methods_go}

func TestAPIError_typed(t *testing.T) {{
\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {{
\t\tw.WriteHeader(http.StatusUnauthorized)
\t\twriteJSON(w, map[string]any{{
\t\t\t"error": map[string]any{{
\t\t\t\t"code":      "UNAUTHORIZED",
\t\t\t\t"message":   "invalid API key",
\t\t\t\t"retryable": false,
\t\t\t}},
\t\t}})
\t}})
\t_, err := {auth_go_call_bad}
\tif err == nil {{
\t\tt.Fatal("expected error, got nil")
\t}}
\tvar apiErr *crucible.APIError
\tif !errors.As(err, &apiErr) {{
\t\tt.Fatalf("expected *crucible.APIError, got %T: %v", err, err)
\t}}
\tif apiErr.Code != "UNAUTHORIZED" {{
\t\tt.Errorf("Code = %q, want %q", apiErr.Code, "UNAUTHORIZED")
\t}}
\tif apiErr.Retryable {{
\t\tt.Error("Retryable should be false")
\t}}
}}

func TestAPIError_retryable(t *testing.T) {{
\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {{
\t\tw.WriteHeader(http.StatusTooManyRequests)
\t\twriteJSON(w, map[string]any{{
\t\t\t"error": map[string]any{{
\t\t\t\t"code":      "RATE_LIMITED",
\t\t\t\t"message":   "slow down",
\t\t\t\t"retryable": true,
\t\t\t}},
\t\t}})
\t}})
\t_, err := {auth_go_call_rate}
\tvar apiErr *crucible.APIError
\tif !errors.As(err, &apiErr) {{
\t\tt.Fatalf("expected *crucible.APIError, got %T", err)
\t}}
\tif !apiErr.Retryable {{
\t\tt.Error("Retryable should be true")
\t}}
}}

func TestAPIError_unknownBody(t *testing.T) {{
\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {{
\t\tw.WriteHeader(http.StatusInternalServerError)
\t\tw.Write([]byte("not json"))
\t}})
\t_, err := c.Healthz(context.Background())
\tvar apiErr *crucible.APIError
\tif !errors.As(err, &apiErr) {{
\t\tt.Fatalf("expected *crucible.APIError, got %T", err)
\t}}
\tif apiErr.Code != "UNKNOWN" {{
\t\tt.Errorf("Code = %q, want %q", apiErr.Code, "UNKNOWN")
\t}}
}}
""")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TypeScript client
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ts_header = (
    "// Code generated by scripts/gen-clients.sh — DO NOT EDIT.\n"
    f"// Source: clients/openapi.json ({title} {version})\n"
)

write(os.path.join(TS_DIR, "src", "errors.ts"), ts_header + """\

/** Shape of the gateway error envelope. */
export interface ErrorBody {
  error: {
    code: string;
    message: string;
    retryable?: boolean;
  };
}

/**
 * ApiError is thrown when the gateway returns a non-2xx status.
 * It models the error envelope: {"error":{"code":"...","message":"...","retryable":true}}.
 */
export class ApiError extends Error {
  readonly code: string;
  readonly retryable: boolean | undefined;
  readonly status: number;

  constructor(status: number, code: string, message: string, retryable?: boolean) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.code = code;
    this.retryable = retryable;
    // Restore prototype chain (required when extending built-ins in ES5 targets).
    Object.setPrototypeOf(this, new.target.prototype);
  }

  static async fromResponse(resp: Response): Promise<ApiError> {
    let code = "UNKNOWN";
    let message = `HTTP ${resp.status}`;
    let retryable: boolean | undefined;
    try {
      const body = (await resp.json()) as ErrorBody;
      code = body.error.code;
      message = body.error.message;
      retryable = body.error.retryable;
    } catch {
      // body is not valid JSON; keep defaults
    }
    return new ApiError(resp.status, code, message, retryable);
  }
}
""")

# ── TypeScript response types ─────────────────────────────────────────────────

def ts_response_type(op):
    schema = op.resp200.get("content", {}).get("application/json", {}).get("schema", {})
    props  = schema.get("properties", {})
    if props and not schema.get("additionalProperties"):
        return go_name(op.op_id) + "Response"
    return "Record<string, unknown>"

def ts_response_interface(op):
    rtype = ts_response_type(op)
    if rtype == "Record<string, unknown>":
        return ""
    schema = op.resp200.get("content", {}).get("application/json", {}).get("schema", {})
    props   = schema.get("properties", {})
    fields  = []
    for fname, fschema in sorted(props.items()):
        ftype = fschema.get("type", "unknown")
        add   = fschema.get("additionalProperties")
        if ftype == "string":
            ts_type = "string"
        elif ftype == "boolean":
            ts_type = "boolean"
        elif ftype == "integer" or ftype == "number":
            ts_type = "number"
        elif ftype == "array":
            ts_type = "unknown[]"
        elif ftype == "object" and add:
            inner   = add.get("type", "unknown")
            ts_type = f"Record<string, {inner}>"
        else:
            ts_type = "unknown"
        fields.append(f"  {fname}: {ts_type};")
    return f"export interface {rtype} {{\n" + "\n".join(fields) + "\n}\n"

interfaces = "".join(iface for op in ops if (iface := ts_response_interface(op)))

def ts_method(op):
    fn    = ts_name(op.op_id)
    rtype = ts_response_type(op)
    path  = op.path

    param_parts = []
    if op.secure and op.has_body:
        # apiKey before payload; use explicit union to avoid required-after-optional TS error.
        param_parts.append("apiKey: string | undefined")
        param_parts.append("payload: Record<string, unknown>")
    elif op.secure:
        param_parts.append("apiKey?: string")
    elif op.has_body:
        param_parts.append("payload: Record<string, unknown>")
    params = ", ".join(param_parts)

    if op.method == "get":
        api_key_expr = "apiKey" if op.secure else "undefined"
        return (
            f"  /** {op.method.upper()} {path} — {op.op_id.replace('_', ' ')}. */\n"
            f"  async {fn}({params}): Promise<{rtype}> {{\n"
            f'    return this.get<{rtype}>("{path}", {api_key_expr});\n'
            f"  }}"
        )
    else:
        api_key_expr = "apiKey ?? this.defaultApiKey" if op.secure else "undefined"
        body_expr    = "payload" if op.has_body else "{}"
        doc_lines    = [
            f"  /**",
            f"   * {op.method.upper()} {path} — {op.op_id.replace('_', ' ')}.",
        ]
        if op.secure:
            doc_lines.append(f"   * @param apiKey - Override the default API key for this call.")
        doc_lines.append("   */")
        doc_block = "\n".join(doc_lines)
        return (
            f"{doc_block}\n"
            f"  async {fn}({params}): Promise<{rtype}> {{\n"
            f'    return this.post<{rtype}>("{path}", {body_expr}, {api_key_expr});\n'
            f"  }}"
        )

methods_ts = "\n\n".join(ts_method(op) for op in ops)

write(os.path.join(TS_DIR, "src", "client.ts"), ts_header + f"""
import {{ ApiError }} from "./errors";

{interfaces}
export interface ClientOptions {{
  /** Override the global fetch implementation (useful in tests). Defaults to globalThis.fetch. */
  fetch?: typeof globalThis.fetch;
  /** Default API key sent as {api_key_header} on authenticated requests. */
  apiKey?: string;
}}

/**
 * Client is a type-safe consumer SDK for the Crucible Gateway.
 * It uses the runtime's fetch with no additional runtime dependencies.
 */
export class Client {{
  private readonly baseURL: string;
  private readonly fetchImpl: typeof globalThis.fetch;
  private readonly defaultApiKey: string | undefined;

  constructor(baseURL: string, options: ClientOptions = {{}}) {{
    // Normalize baseURL: strip query, fragment, and credentials (mirrors Go client).
    try {{
      const u = new URL(baseURL);
      u.search = "";
      u.hash = "";
      u.username = "";
      u.password = "";
      baseURL = u.toString();
    }} catch {{
      // Non-absolute URL — use as-is (e.g. relative path in tests).
    }}
    this.baseURL = baseURL.replace(/\\/+$/u, "");
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.defaultApiKey = options.apiKey;
  }}

{methods_ts}

  private async get<T>(path: string, apiKey?: string): Promise<T> {{
    const headers: Record<string, string> = {{ Accept: "application/json" }};
    if (apiKey) {{
      headers["{api_key_header}"] = apiKey;
    }}
    const resp = await this.fetchImpl(this.baseURL + path, {{
      method: "GET",
      headers,
    }});
    if (!resp.ok) {{
      throw await ApiError.fromResponse(resp);
    }}
    return resp.json() as Promise<T>;
  }}

  private async post<T>(path: string, body: unknown, apiKey?: string): Promise<T> {{
    const headers: Record<string, string> = {{
      "Content-Type": "application/json",
      Accept: "application/json",
    }};
    if (apiKey) {{
      headers["{api_key_header}"] = apiKey;
    }}
    const resp = await this.fetchImpl(this.baseURL + path, {{
      method: "POST",
      headers,
      body: JSON.stringify(body),
    }});
    if (!resp.ok) {{
      throw await ApiError.fromResponse(resp);
    }}
    return resp.json() as Promise<T>;
  }}
}}
""")

# ── src/index.ts ──────────────────────────────────────────────────────────────
type_exports = ", ".join(
    t for op in ops
    if (t := ts_response_type(op)) != "Record<string, unknown>"
)
type_export_line = (
    f'export type {{ ClientOptions{", " + type_exports if type_exports else ""} }} from "./client";\n'
)

write(os.path.join(TS_DIR, "src", "index.ts"), ts_header + (
    f'export {{ Client }} from "./client";\n'
    f'{type_export_line}'
    f'export {{ ApiError }} from "./errors";\n'
    f'export type {{ ErrorBody }} from "./errors";\n'
))

# ── test/client.test.ts ───────────────────────────────────────────────────────

def ts_test_method(op):
    fn    = ts_name(op.op_id)
    rtype = ts_response_type(op)

    schema = op.resp200.get("content", {}).get("application/json", {}).get("schema", {})
    props  = schema.get("properties", {})

    # Build mock response body.
    if rtype == "Record<string, unknown>":
        mock_body = '{"result":"ok"}'
    else:
        sample = {}
        for p in sorted(props.keys()):
            pschema = props[p]
            if pschema.get("type") == "string":
                sample[p] = "ok"
            elif pschema.get("type") == "object":
                sample[p] = {"db": "ok"}
        mock_body = json.dumps(sample)

    # Build client call (apiKey before payload to match updated ts_method signature).
    if op.has_body and op.secure:
        call = f'await c.{fn}("key", {{}})'
    elif op.has_body:
        call = f'await c.{fn}({{}})'
    elif op.secure:
        call = f'await c.{fn}("key")'
    else:
        call = f'await c.{fn}()'

    # Build assertion: use first string-typed property for equality check.
    first_str_prop = next(
        (p for p in sorted(props.keys()) if props[p].get("type") == "string"),
        None
    ) if props else None

    if op.method == "post" and op.secure:
        lines = [
            f'describe("Client.{fn}", () => {{',
            f'  it("sends {api_key_header} header and returns {rtype} on 200", async () => {{',
            f'    let capturedInit: RequestInit | undefined;',
            f'    const capFetch: typeof globalThis.fetch = async (_url, init) => {{',
            f'      capturedInit = init;',
            f'      return new Response(JSON.stringify({mock_body}), {{',
            f'        status: 200, headers: {{ "Content-Type": "application/json" }},',
            f'      }});',
            f'    }};',
            f'    const c = new Client("http://gw.test", {{ fetch: capFetch }});',
            f'    const got = {call};',
        ]
        if first_str_prop:
            lines.append(f'    assert.equal(got.{first_str_prop}, "ok");')
        elif rtype == "Record<string, unknown>":
            lines.append(f'    assert.equal(got["result"], "ok");')
        else:
            lines.append(f'    assert.ok(got);')
        lines += [
            f'    assert.ok(capturedInit, "capFetch was not called");',
            f'    const hdrs = capturedInit!.headers as Record<string, string>;',
            f'    assert.equal(hdrs["{api_key_header}"], "key");',
            f'  }});',
            f'}});',
        ]
    else:
        lines = [
            f'describe("Client.{fn}", () => {{',
            f'  it("returns typed {rtype} on 200", async () => {{',
            f'    const c = new Client("http://gw.test", {{ fetch: mockFetch(200, {mock_body}) }});',
            f'    const got = {call};',
        ]
        if first_str_prop:
            lines.append(f'    assert.equal(got.{first_str_prop}, "ok");')
        elif rtype == "Record<string, unknown>":
            lines.append(f'    assert.equal(got["result"], "ok");')
        else:
            lines.append(f'    assert.ok(got);')
        lines += ['  });', '});']
    return "\n".join(lines)

ts_test_methods = "\n\n".join(ts_test_method(op) for op in ops)

# Error test uses first authenticated POST operation (dynamically resolved).
if first_auth_post:
    auth_ts_fn = ts_name(first_auth_post.op_id)
    if first_auth_post.has_body:
        # apiKey is first param (string | undefined); pass undefined to test error handling.
        auth_ts_call = f'() => c.{auth_ts_fn}(undefined, {{}})'
    else:
        auth_ts_call = f'() => c.{auth_ts_fn}()'
else:
    auth_ts_call = '() => c.healthz()'

write(os.path.join(TS_DIR, "test", "client.test.ts"), ts_header + f"""\
import {{ describe, it }} from "node:test";
import assert from "node:assert/strict";
import {{ Client, ApiError }} from "../src/index";

function mockFetch(status: number, body: unknown): typeof globalThis.fetch {{
  return async (_url: string | URL | Request, _init?: RequestInit): Promise<Response> => {{
    return new Response(JSON.stringify(body), {{
      status,
      headers: {{ "Content-Type": "application/json" }},
    }});
  }};
}}

{ts_test_methods}

describe("ApiError", () => {{
  it("is an instance of Error", () => {{
    const err = new ApiError(500, "TEST", "test error");
    assert.ok(err instanceof Error);
    assert.equal(err.message, "test error");
    assert.equal(err.code, "TEST");
    assert.equal(err.name, "ApiError");
  }});

  it("fromResponse parses error envelope", async () => {{
    const resp = new Response(
      JSON.stringify({{ error: {{ code: "QUOTA_EXCEEDED", message: "over limit", retryable: true }} }}),
      {{ status: 402 }},
    );
    const err = await ApiError.fromResponse(resp);
    assert.equal(err.code, "QUOTA_EXCEEDED");
    assert.equal(err.retryable, true);
    assert.equal(err.status, 402);
  }});

  it("fromResponse handles non-JSON body gracefully", async () => {{
    const resp = new Response("not json", {{ status: 503 }});
    const err = await ApiError.fromResponse(resp);
    assert.equal(err.code, "UNKNOWN");
    assert.equal(err.status, 503);
  }});

  it("throws ApiError with typed code on 401", async () => {{
    const c = new Client("http://gw.test", {{
      fetch: mockFetch(401, {{ error: {{ code: "UNAUTHORIZED", message: "bad key", retryable: false }} }}),
    }});
    await assert.rejects(
      {auth_ts_call},
      (err: unknown) => {{
        assert.ok(err instanceof ApiError);
        assert.equal(err.code, "UNAUTHORIZED");
        assert.equal(err.retryable, false);
        return true;
      }},
    );
  }});

  it("throws ApiError with retryable=true on 429", async () => {{
    const c = new Client("http://gw.test", {{
      fetch: mockFetch(429, {{ error: {{ code: "RATE_LIMITED", message: "slow down", retryable: true }} }}),
    }});
    await assert.rejects(
      {auth_ts_call},
      (err: unknown) => {{
        assert.ok(err instanceof ApiError);
        assert.equal(err.code, "RATE_LIMITED");
        assert.equal(err.retryable, true);
        return true;
      }},
    );
  }});
}});
""")

print(f"Generated clients from {os.path.basename(SPEC_PATH)} ({title} {version})")
print(f"  Go:         {GO_DIR}")
print(f"  TypeScript: {TS_DIR}")
PYEOF
