#!/usr/bin/env bash
# gen-clients.sh — regenerate Go and TypeScript consumer client SDKs from
# clients/openapi.json. Idempotent: a second run produces zero git diff.
# Requirements: python3 (stdlib only), go 1.22+.
#
# clients/openapi.json is itself a generated artifact: `go run
# ./gateway/cmd/spec-dump` renders the gateway's real served OpenAPI document
# (openapi.Build + openapi.Handler); .github/workflows/client-sdk-drift.yml
# fails the build if the committed snapshot differs from that command's
# output, so this generator's input can never silently drift from the
# gateway's actual /openapi.json.
#
# Supports GET/POST/DELETE/PATCH operations, {param} path segments, and
# query parameters (typed as string or integer). Skips PUT/HEAD/OPTIONS/TRACE
# and billing-tagged routes (see notes on stderr).
#
# Drift check (run locally or in CI to assert no hand-edits have diverged):
#   bash scripts/gen-clients.sh && git diff --exit-code \
#     clients/go/client.go clients/go/errors.go \
#     clients/typescript/src/client.ts clients/typescript/src/errors.ts \
#     clients/typescript/src/index.ts
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SPEC="${REPO_ROOT}/clients/openapi.json"

if [[ ! -f "${SPEC}" ]]; then
  echo "error: spec not found at ${SPEC}" >&2
  exit 1
fi

python3 - "${SPEC}" "${REPO_ROOT}" <<'PYEOF'
import json, os, re, sys

SPEC_PATH = sys.argv[1]
REPO_ROOT  = sys.argv[2]
GO_DIR     = os.path.join(REPO_ROOT, "clients", "go")
TS_DIR     = os.path.join(REPO_ROOT, "clients", "typescript")

with open(SPEC_PATH) as f:
    spec = json.load(f)

info = spec.get("info")
if not info or not isinstance(info, dict):
    print("error: spec missing 'info' object", file=sys.stderr)
    sys.exit(1)
for _req in ("title", "version"):
    if _req not in info:
        print(f"error: spec.info missing required field '{_req}'", file=sys.stderr)
        sys.exit(1)
title   = info["title"].replace("\n", " ").replace("\r", " ")
version = info["version"].replace("\n", " ").replace("\r", " ")
header  = (
    f"// Code generated by scripts/gen-clients.sh — DO NOT EDIT.\n"
    f"// Source: clients/openapi.json ({title} {version})\n"
)

paths = spec.get("paths")
if not isinstance(paths, dict):
    print("error: spec missing 'paths' object", file=sys.stderr)
    sys.exit(1)

# ── API-key header name from securitySchemes ─────────────────────────────────
api_key_header = "X-API-Key"
for scheme in spec.get("components", {}).get("securitySchemes", {}).values():
    if scheme.get("type") == "apiKey" and scheme.get("in") == "header":
        api_key_header = scheme.get("name", api_key_header)
        break

# ── operationId → Go TitleCase / TS camelCase ────────────────────────────────
def go_name(op_id):
    return "".join(p.capitalize() for p in op_id.split("_"))

def ts_name(op_id):
    parts = op_id.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])

# param_arg_name converts a snake_case path/query parameter name (e.g.
# "per_page") to a camelCase local variable / argument name valid in both
# Go and TypeScript ("perPage"). Single-word names (e.g. "id") pass through.
def param_arg_name(name):
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])

# ── Collect typed operations (skip billing/text-plain/unsupported) ──────────
class Op:
    def __init__(self, path, method, op):
        self.path        = path
        self.method      = method
        self.op_id       = op["operationId"]
        self.tags        = op.get("tags", [])
        self.secure      = bool(op.get("security"))
        self.has_body    = bool(op.get("requestBody"))
        self.path_params = re.findall(r"\{(\w+)\}", path)
        self.query_params = [
            (p["name"], (p.get("schema") or {}).get("type", "string"))
            for p in op.get("parameters", [])
            if p.get("in") == "query"
        ]
        responses = op.get("responses", {})
        self.success_code = next((c for c in ("200", "201", "204") if c in responses), None)
        resp = responses.get(self.success_code, {}) if self.success_code else {}
        self.resp       = resp
        # A 204 (or any success response with no content body) has no JSON to decode.
        self.no_content = self.success_code == "204" or not resp.get("content")
        self.json_ok    = "application/json" in resp.get("content", {})

ops = []
_all_methods = ("get", "post", "put", "delete", "patch", "head", "options", "trace")
_gen_methods  = ("get", "post", "delete", "patch")
for path, item in sorted(paths.items()):
    for method in _all_methods:
        if method not in item:
            continue
        if method not in _gen_methods:
            print(f"note: skipping {method.upper()} {path} (only GET/POST/DELETE/PATCH are generated; add support to gen-clients.sh to include this method)", file=sys.stderr)
            continue
        op = Op(path, method, item[method])
        if "billing" in op.tags:
            print(f"note: skipping {method.upper()} {path} (billing tag excluded)", file=sys.stderr)
            continue
        if op.success_code is None:
            print(f"note: skipping {method.upper()} {path} (no 2xx success response)", file=sys.stderr)
            continue
        if not op.no_content and not op.json_ok:
            print(f"note: skipping {method.upper()} {path} (no application/json success response)", file=sys.stderr)
            continue
        ops.append(op)

# Find first authenticated POST op (used in error test stubs).
first_auth_post = next((op for op in ops if op.secure and op.method == "post"), None)
if not first_auth_post:
    print("error: no authenticated POST operation found; cannot generate error tests", file=sys.stderr)
    sys.exit(1)

# First op with query parameters (used for a dedicated query-encoding test).
first_query_op = next((op for op in ops if op.query_params), None)

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Go client
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Read module path and Go version from existing go.mod if present; preserves clone-and-adapt renames.
go_mod_path = os.path.join(GO_DIR, "go.mod")
go_module = "github.com/Unluckyathecking/crucible/clients/go"
go_version = "1.22"
if os.path.exists(go_mod_path):
    with open(go_mod_path) as _f:
        for _line in _f:
            if _line.startswith("module "):
                go_module = _line.split()[1].strip()
            elif _line.startswith("go "):
                go_version = _line.split()[1].strip()

write(go_mod_path, f"""\
{header}
module {go_module}

go {go_version}
""")

# Overrides the repo-root go.work so `cd clients/go && go build ./...` works.
write(os.path.join(GO_DIR, "go.work"), f"""\
go {go_version}

use .
""")

write(os.path.join(GO_DIR, "errors.go"), f"""\
{header}
package crucible

import "fmt"

// APIError is returned when the gateway responds with a non-2xx status.
// It models the error envelope: {{"error":{{"code":"...","message":"...","retryable":true}}}}.
type APIError struct {{
\tCode      string
\tMessage   string
\tRetryable bool
}}

func (e *APIError) Error() string {{
\treturn fmt.Sprintf("crucible: %s: %s (retryable=%v)", e.Code, e.Message, e.Retryable)
}}
""")

# ── Response types ────────────────────────────────────────────────────────────

def go_response_type(op):
    if op.no_content:
        return None
    schema = op.resp.get("content", {}).get("application/json", {}).get("schema", {})
    props  = schema.get("properties", {})
    if props and not schema.get("additionalProperties"):
        return go_name(op.op_id) + "Response"
    return "map[string]any"

def go_response_structs():
    parts = []
    for op in ops:
        rtype = go_response_type(op)
        if rtype in (None, "map[string]any"):
            continue
        schema = op.resp.get("content", {}).get("application/json", {}).get("schema", {})
        props   = schema.get("properties", {})
        fields  = []
        for fname, fschema in sorted(props.items()):
            go_field = fname.capitalize()
            ftype = fschema.get("type", "any")
            add   = fschema.get("additionalProperties")
            if ftype == "string":
                go_type = "string"
            elif ftype == "boolean":
                go_type = "bool"
            elif ftype == "integer":
                go_type = "int64"
            elif ftype == "number":
                go_type = "float64"
            elif ftype == "array":
                go_type = "[]any"
            elif ftype == "object" and add:
                inner    = add.get("type", "any")
                inner_go = {"string": "string", "integer": "int64", "number": "float64", "boolean": "bool"}.get(inner, "any")
                go_type  = f"map[string]{inner_go}"
            else:
                go_type = "any"
            fields.append(f'\t{go_field} {go_type} `json:"{fname}"`')
        field_block = "\n".join(fields)
        parts.append(
            f"// {rtype} is returned by {go_name(op.op_id)}.\n"
            f"type {rtype} struct {{\n{field_block}\n}}"
        )
    return "\n\n".join(parts) + ("\n\n" if parts else "")

# Any integer query parameter across all ops needs strconv for formatting;
# only import it when actually used so unused-import can never fail the build.
_needs_strconv = any(ptype == "integer" for op in ops for _, ptype in op.query_params)

def go_method_signature_params(op):
    params = ["ctx context.Context"]
    if op.secure:
        params.append("apiKey string")
    for p in op.path_params:
        params.append(f"{param_arg_name(p)} string")
    if op.has_body:
        params.append("payload any")
    for name, ptype in op.query_params:
        go_type = "int64" if ptype == "integer" else "string"
        params.append(f"{param_arg_name(name)} {go_type}")
    return ", ".join(params)

def go_path_and_query_lines(op):
    """Returns (lines, path_expr): lines build any local vars needed to resolve
    the request path (path-param substitution and/or a query string), and
    path_expr is the Go expression to pass as the request path."""
    lines = []
    path_var = None
    if op.path_params:
        fmt_path = re.sub(r"\{(\w+)\}", "%s", op.path)
        args = ", ".join(f"url.PathEscape({param_arg_name(p)})" for p in op.path_params)
        lines.append(f'\tpath := fmt.Sprintf("{fmt_path}", {args})')
        path_var = "path"

    if op.query_params:
        lines.append("\tq := url.Values{}")
        for name, ptype in op.query_params:
            arg = param_arg_name(name)
            if ptype == "integer":
                lines.append(f"\tif {arg} != 0 {{")
                lines.append(f'\t\tq.Set("{name}", strconv.FormatInt({arg}, 10))')
                lines.append("\t}")
            else:
                lines.append(f'\tif {arg} != "" {{')
                lines.append(f'\t\tq.Set("{name}", {arg})')
                lines.append("\t}")
        if path_var is None:
            lines.append(f'\treqPath := "{op.path}"')
            path_var = "reqPath"
        lines.append("\tif len(q) > 0 {")
        lines.append(f'\t\t{path_var} += "?" + q.Encode()')
        lines.append("\t}")

    path_expr = path_var if path_var is not None else f'"{op.path}"'
    return lines, path_expr

def go_method(op):
    fn    = go_name(op.op_id)
    rtype = go_response_type(op)
    method_const = {
        "get": "http.MethodGet", "post": "http.MethodPost",
        "delete": "http.MethodDelete", "patch": "http.MethodPatch",
    }[op.method]

    param_str = go_method_signature_params(op)
    path_lines, path_expr = go_path_and_query_lines(op)

    if rtype is None:
        ret_sig = "error"
        nil_ret = ""
    elif rtype == "map[string]any":
        ret_sig = "(map[string]any, error)"
        nil_ret = "nil, "
    else:
        ret_sig = f"(*{rtype}, error)"
        nil_ret = "nil, "

    lines = [f"// {fn} calls {op.method.upper()} {op.path} ({op.op_id.replace('_', ' ')})."]
    if op.secure:
        lines.append(f"// apiKey is sent as the {api_key_header} header.")
    lines.append(f"func (c *Client) {fn}({param_str}) {ret_sig} {{")
    if op.has_body:
        lines += [
            "\tbody, err := json.Marshal(payload)",
            "\tif err != nil {",
            f'\t\treturn {nil_ret}fmt.Errorf("crucible: marshal payload: %w", err)',
            "\t}",
        ]
    lines += path_lines
    api_key_arg = "apiKey" if op.secure else '""'
    body_arg    = "body"   if op.has_body else "nil"
    lines += [
        f'\tresp, err := c.do(ctx, {method_const}, {path_expr}, {api_key_arg}, {body_arg})',
        "\tif err != nil {",
        f"\t\treturn {nil_ret}err",
        "\t}",
        "\tdefer resp.Body.Close()",
        "\tif err := checkError(resp); err != nil {",
        f"\t\treturn {nil_ret}err",
        "\t}",
    ]
    if rtype is None:
        lines.append("\treturn nil")
    elif rtype == "map[string]any":
        lines += [
            "\tout := make(map[string]any)",
            "\tif decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {",
            '\t\treturn nil, fmt.Errorf("crucible: decode response: %w", decErr)',
            "\t}",
            "\tif out == nil {",
            "\t\tout = make(map[string]any)",
            "\t}",
            "\treturn out, nil",
        ]
    else:
        lines += [
            f"\tvar out {rtype}",
            "\tif decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {",
            '\t\treturn nil, fmt.Errorf("crucible: decode response: %w", decErr)',
            "\t}",
            "\treturn &out, nil",
        ]
    lines.append("}")
    return "\n".join(lines)

structs_go = go_response_structs()
methods_go = "\n\n".join(go_method(op) for op in ops)

go_imports = ["bytes", "context", "encoding/json", "fmt", "io", "net/http", "net/url"]
if _needs_strconv:
    go_imports.append("strconv")
go_imports.append("strings")
go_imports_block = "\n".join(f'\t"{imp}"' for imp in go_imports)

write(os.path.join(GO_DIR, "client.go"), f"""\
{header}
// Package crucible is a type-safe Go client for the Crucible Gateway API.
// Construct a Client with New; all timeouts are the caller's responsibility.
package crucible

import (
{go_imports_block}
)

// Client calls the Crucible Gateway. Construct with New.
type Client struct {{
\tbaseURL *url.URL
\thttp    *http.Client
}}

// New returns a Client targeting baseURL, or an error if baseURL cannot be parsed.
// httpClient defaults to http.DefaultClient when nil. Note: http.DefaultClient has no
// timeout; callers must supply a client with Timeout set or use context.WithTimeout.
// baseURL is normalized: query strings, fragments, and credentials are stripped; trailing
// slashes on the path are removed so that appending spec paths (which start with "/") is correct.
// Any base path prefix (e.g. "/crucible" for a reverse-proxy subpath) is preserved.
func New(baseURL string, httpClient *http.Client) (*Client, error) {{
\tif httpClient == nil {{
\t\thttpClient = http.DefaultClient
\t}}
\tu, err := url.Parse(baseURL)
\tif err != nil {{
\t\treturn nil, fmt.Errorf("crucible: invalid baseURL %q: %w", baseURL, err)
\t}}
\tu.RawQuery = ""
\tu.Fragment = ""
\tu.User = nil
\tu.Path = strings.TrimRight(u.Path, "/")
\treturn &Client{{baseURL: u, http: httpClient}}, nil
}}

{structs_go}{methods_go}

func (c *Client) do(ctx context.Context, method, path, apiKey string, body []byte) (*http.Response, error) {{
\t// Append path directly: c.baseURL has no trailing slash; path starts with "/".
\t// This preserves any base path prefix (e.g. a reverse-proxy subpath).
\treqURL := c.baseURL.String() + path
\tvar req *http.Request
\tvar err error
\tif body != nil {{
\t\treq, err = http.NewRequestWithContext(ctx, method, reqURL, bytes.NewReader(body))
\t}} else {{
\t\treq, err = http.NewRequestWithContext(ctx, method, reqURL, nil)
\t}}
\tif err != nil {{
\t\treturn nil, fmt.Errorf("crucible: build request: %w", err)
\t}}
\tif body != nil {{
\t\treq.Header.Set("Content-Type", "application/json")
\t}}
\tif apiKey != "" {{
\t\treq.Header.Set("{api_key_header}", apiKey)
\t}}
\treq.Header.Set("Accept", "application/json")
\treturn c.http.Do(req)
}}

// checkError returns nil for 2xx responses without touching resp.Body.
// For non-2xx it reads the body (bounded to 64 KiB) to decode the gateway
// error envelope. The caller's defer resp.Body.Close() handles cleanup.
func checkError(resp *http.Response) error {{
\tif resp.StatusCode >= 200 && resp.StatusCode < 300 {{
\t\treturn nil
\t}}
\tvar envelope struct {{
\t\tError struct {{
\t\t\tCode      string `json:"code"`
\t\t\tMessage   string `json:"message"`
\t\t\tRetryable bool   `json:"retryable"`
\t\t}} `json:"error"`
\t}}
\t// Read up to 64 KiB + 1; the extra byte lets us detect oversized bodies explicitly.
\tconst limit = 64 << 10
\tbody, readErr := io.ReadAll(io.LimitReader(resp.Body, limit+1))
\tif readErr != nil {{
\t\treturn &APIError{{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (read body: %v)", resp.StatusCode, readErr)}}
\t}}
\tif len(body) > limit {{
\t\t// Best-effort bounded drain; connection may not be reusable if body exceeds ~68 KiB.
\t\t_, _ = io.CopyN(io.Discard, resp.Body, 4<<10)
\t\treturn &APIError{{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (error body >%d bytes)", resp.StatusCode, limit)}}
\t}}
\tif decErr := json.Unmarshal(body, &envelope); decErr != nil {{
\t\treturn &APIError{{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (invalid JSON: %v)", resp.StatusCode, decErr)}}
\t}}
\tif envelope.Error.Code == "" {{
\t\treturn &APIError{{Code: "UNKNOWN", Message: fmt.Sprintf("HTTP %d (missing error code)", resp.StatusCode)}}
\t}}
\treturn &APIError{{
\t\tCode:      envelope.Error.Code,
\t\tMessage:   envelope.Error.Message,
\t\tRetryable: envelope.Error.Retryable,
\t}}
}}
""")

# ── client_test.go ────────────────────────────────────────────────────────────

def go_test_call_args(op, with_key_literal=None):
    """Builds the call-site argument list in the same order as
    go_method_signature_params (minus ctx, which callers add explicitly)."""
    args = []
    if op.secure:
        args.append(f'"{with_key_literal}"' if with_key_literal else '"test-key"')
    for p in op.path_params:
        args.append(f'"test-{p}"')
    if op.has_body:
        args.append("map[string]any{\"x\": 1}")
    for name, ptype in op.query_params:
        args.append("0" if ptype == "integer" else '""')
    return args

def go_test_method(op):
    fn    = go_name(op.op_id)
    rtype = go_response_type(op)
    method_const = {
        "get": "http.MethodGet", "post": "http.MethodPost",
        "delete": "http.MethodDelete", "patch": "http.MethodPatch",
    }[op.method]

    test_path = op.path
    for p in op.path_params:
        test_path = test_path.replace("{" + p + "}", "test-" + p)

    schema = op.resp.get("content", {}).get("application/json", {}).get("schema", {}) if not op.no_content else {}
    props  = schema.get("properties", {})

    if rtype is None:
        resp_lines = ["\t\tw.WriteHeader(http.StatusNoContent)"]
    elif rtype == "map[string]any":
        resp_lines = ['\t\twriteJSON(w, map[string]any{"result": "ok"})']
    else:
        field_parts = []
        for fname in sorted(props.keys()):
            fschema = props[fname]
            ftype = fschema.get("type")
            if ftype == "string":
                field_parts.append(f'"{fname}": "ok"')
            elif ftype == "object":
                field_parts.append(f'"{fname}": map[string]any{{"db": "ok"}}')
            elif ftype == "integer" or ftype == "number":
                field_parts.append(f'"{fname}": 1')
            elif ftype == "boolean":
                field_parts.append(f'"{fname}": true')
            elif ftype == "array":
                field_parts.append(f'"{fname}": []any{{}}')
        resp_json = "map[string]any{" + ", ".join(field_parts) + "}"
        resp_lines = [f"\t\twriteJSON(w, {resp_json})"]

    call = f"c.{fn}(context.Background(), {', '.join(go_test_call_args(op))})" if go_test_call_args(op) else f"c.{fn}(context.Background())"

    lines = [
        f"func Test{fn}(t *testing.T) {{",
        f'\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {{',
        f'\t\tif r.Method != {method_const} || r.URL.Path != "{test_path}" {{',
        f'\t\t\tt.Errorf("unexpected request %s %s", r.Method, r.URL.Path)',
        "\t\t}",
    ]
    if op.secure:
        lines += [
            f'\t\tif got := r.Header.Get("{api_key_header}"); got == "" {{',
            f'\t\t\tt.Error("{api_key_header} header missing")',
            "\t\t}",
        ]
    if op.has_body:
        lines += [
            "\t\tvar reqBody map[string]any",
            "\t\tif err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {",
            '\t\t\tt.Fatalf("decode request body: %v", err)',
            "\t\t}",
            '\t\tif reqBody["x"] == nil {',
            '\t\t\tt.Error("expected request body to contain key x")',
            "\t\t}",
        ]
    lines += resp_lines
    lines += ["\t})"]

    if rtype is None:
        lines += [
            f"\terr := {call}",
            "\tif err != nil {",
            "\t\tt.Fatal(err)",
            "\t}",
            "}",
        ]
    elif rtype == "map[string]any":
        lines += [
            f"\tgot, err := {call}",
            "\tif err != nil {",
            "\t\tt.Fatal(err)",
            "\t}",
            "\tif got == nil {",
            '\t\tt.Fatal("expected non-nil map, got nil")',
            "\t}",
            '\tif got["result"] != "ok" {',
            '\t\tt.Errorf("result = %v, want \\"ok\\"", got["result"])',
            "\t}",
            "}",
        ]
    else:
        first_str_field = next(
            (fname for fname in sorted(props.keys()) if props[fname].get("type") == "string"),
            None
        )
        if first_str_field:
            go_field = first_str_field.capitalize()
            lines += [
                f"\tresp, err := {call}",
                "\tif err != nil {",
                "\t\tt.Fatal(err)",
                "\t}",
                f'\tif resp.{go_field} != "ok" {{',
                f'\t\tt.Errorf("{go_field} = %q, want %q", resp.{go_field}, "ok")',
                "\t}",
                "}",
            ]
        else:
            lines += [
                f"\t_, err := {call}",
                "\tif err != nil {",
                "\t\tt.Fatal(err)",
                "\t}",
                "}",
            ]
    return "\n".join(lines)

test_methods_go = "\n\n".join(go_test_method(op) for op in ops)

# Null-body regression test: JSON "null" response should produce empty map, not nil.
first_map_op = next((op for op in ops if go_response_type(op) == "map[string]any"), None)
null_body_test_go = ""
if first_map_op:
    fn_nb = go_name(first_map_op.op_id)
    nb_args = go_test_call_args(first_map_op)
    nb_call = f"c.{fn_nb}(context.Background(), {', '.join(nb_args)})" if nb_args else f"c.{fn_nb}(context.Background())"
    null_body_test_go = "\n\n" + "\n".join([
        f"func Test{fn_nb}_nullBody(t *testing.T) {{",
        '\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {',
        '\t\tw.Header().Set("Content-Type", "application/json")',
        '\t\tw.Write([]byte("null"))',
        '\t})',
        f'\tgot, err := {nb_call}',
        '\tif err != nil {',
        '\t\tt.Fatalf("unexpected error: %v", err)',
        '\t}',
        '\tif got == nil {',
        '\t\tt.Error("expected non-nil map for null JSON body, got nil")',
        '\t}',
        '\tif len(got) != 0 {',
        '\t\tt.Errorf("expected empty map, got %v", got)',
        '\t}',
        '}',
    ])

# Query-encoding regression test: verifies typed query args are URL-encoded correctly.
query_encoding_test_go = ""
if first_query_op:
    fn_q = go_name(first_query_op.op_id)
    call_parts = []
    if first_query_op.secure:
        call_parts.append('"test-key"')
    for p in first_query_op.path_params:
        call_parts.append(f'"test-{p}"')
    if first_query_op.has_body:
        call_parts.append('map[string]any{"x": 1}')
    query_checks = []
    for name, ptype in first_query_op.query_params:
        if ptype == "integer":
            call_parts.append("2")
            query_checks.append((name, "2"))
        else:
            call_parts.append('"v"')
            query_checks.append((name, "v"))
    call_q = f"c.{fn_q}(context.Background(), {', '.join(call_parts)})"
    check_lines = "\n".join(
        f'\t\tif got := r.URL.Query().Get("{name}"); got != "{val}" {{\n'
        f'\t\t\tt.Errorf("query {name} = %q, want %q", got, "{val}")\n'
        f'\t\t}}'
        for name, val in query_checks
    )
    query_encoding_test_go = "\n\n" + "\n".join([
        f"func Test{fn_q}_queryEncoding(t *testing.T) {{",
        '\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {',
        check_lines,
        '\t\twriteJSON(w, map[string]any{})',
        '\t})',
        f'\t_, _ = {call_q}',
        '}',
    ])

# Error tests use the first authenticated POST operation (guaranteed non-None after sys.exit check).
auth_go_fn = go_name(first_auth_post.op_id)
if first_auth_post.has_body:
    auth_go_call_bad  = f'c.{auth_go_fn}(context.Background(), "bad-key", map[string]any{{}})'
    auth_go_call_rate = f'c.{auth_go_fn}(context.Background(), "key", map[string]any{{}})'
else:
    auth_go_call_bad  = f'c.{auth_go_fn}(context.Background(), "bad-key")'
    auth_go_call_rate = f'c.{auth_go_fn}(context.Background(), "key")'

write(os.path.join(GO_DIR, "client_test.go"), f"""\
{header}
package crucible_test

import (
\t"context"
\t"encoding/json"
\t"errors"
\t"net/http"
\t"net/http/httptest"
\t"testing"

\tcrucible "{go_module}"
)

func newClient(t *testing.T, handler http.HandlerFunc) *crucible.Client {{
\tt.Helper()
\tsrv := httptest.NewServer(handler)
\tt.Cleanup(srv.Close)
\tc, err := crucible.New(srv.URL, srv.Client())
\tif err != nil {{
\t\tt.Fatalf("crucible.New: %v", err)
\t}}
\treturn c
}}

func writeJSON(w http.ResponseWriter, v any) {{
\tw.Header().Set("Content-Type", "application/json")
\tif err := json.NewEncoder(w).Encode(v); err != nil {{
\t\tpanic(err)
\t}}
}}

{test_methods_go}{null_body_test_go}{query_encoding_test_go}

func TestAPIError_typed(t *testing.T) {{
\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {{
\t\tw.WriteHeader(http.StatusUnauthorized)
\t\twriteJSON(w, map[string]any{{
\t\t\t"error": map[string]any{{
\t\t\t\t"code":      "UNAUTHORIZED",
\t\t\t\t"message":   "invalid API key",
\t\t\t\t"retryable": false,
\t\t\t}},
\t\t}})
\t}})
\t_, err := {auth_go_call_bad}
\tif err == nil {{
\t\tt.Fatal("expected error, got nil")
\t}}
\tvar apiErr *crucible.APIError
\tif !errors.As(err, &apiErr) {{
\t\tt.Fatalf("expected *crucible.APIError, got %T: %v", err, err)
\t}}
\tif apiErr.Code != "UNAUTHORIZED" {{
\t\tt.Errorf("Code = %q, want %q", apiErr.Code, "UNAUTHORIZED")
\t}}
\tif apiErr.Retryable {{
\t\tt.Error("Retryable should be false")
\t}}
}}

func TestAPIError_retryable(t *testing.T) {{
\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {{
\t\tw.WriteHeader(http.StatusTooManyRequests)
\t\twriteJSON(w, map[string]any{{
\t\t\t"error": map[string]any{{
\t\t\t\t"code":      "RATE_LIMITED",
\t\t\t\t"message":   "slow down",
\t\t\t\t"retryable": true,
\t\t\t}},
\t\t}})
\t}})
\t_, err := {auth_go_call_rate}
\tvar apiErr *crucible.APIError
\tif !errors.As(err, &apiErr) {{
\t\tt.Fatalf("expected *crucible.APIError, got %T", err)
\t}}
\tif !apiErr.Retryable {{
\t\tt.Error("Retryable should be true")
\t}}
}}

func TestAPIError_unknownBody(t *testing.T) {{
\tc := newClient(t, func(w http.ResponseWriter, r *http.Request) {{
\t\tw.WriteHeader(http.StatusInternalServerError)
\t\tw.Write([]byte("not json"))
\t}})
\t_, err := {auth_go_call_bad}
\tvar apiErr *crucible.APIError
\tif !errors.As(err, &apiErr) {{
\t\tt.Fatalf("expected *crucible.APIError, got %T", err)
\t}}
\tif apiErr.Code != "UNKNOWN" {{
\t\tt.Errorf("Code = %q, want %q", apiErr.Code, "UNKNOWN")
\t}}
}}
""")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TypeScript client
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ts_header = (
    "// Code generated by scripts/gen-clients.sh — DO NOT EDIT.\n"
    f"// Source: clients/openapi.json ({title} {version})\n"
)

write(os.path.join(TS_DIR, "src", "errors.ts"), ts_header + """\

/** Shape of the gateway error envelope. */
export interface ErrorBody {
  error: {
    code: string;
    message: string;
    retryable?: boolean;
  };
}

/**
 * ApiError is thrown when the gateway returns a non-2xx status.
 * It models the error envelope: {"error":{"code":"...","message":"...","retryable":true}}.
 */
export class ApiError extends Error {
  readonly code: string;
  readonly retryable: boolean | undefined;
  readonly status: number;

  constructor(status: number, code: string, message: string, retryable?: boolean) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.code = code;
    this.retryable = retryable;
    // Restore prototype chain (required when extending built-ins in ES5 targets).
    Object.setPrototypeOf(this, new.target.prototype);
  }

  static async fromResponse(resp: Response): Promise<ApiError> {
    if (resp.bodyUsed) {
      return new ApiError(resp.status, "UNKNOWN", `HTTP ${resp.status} (body already consumed)`);
    }
    let code = "UNKNOWN";
    let message = `HTTP ${resp.status}`;
    let retryable: boolean | undefined;
    try {
      const body = (await resp.json()) as ErrorBody;
      // Use || / ?? so the defensive defaults survive a partial error object ({"error":{}}).
      // If body.error is missing entirely (e.g. body is {}), body.error.code throws and
      // the catch block below handles it — the || guards only apply when error exists.
      code = body.error.code || code;
      message = body.error.message || message;
      retryable = body.error.retryable ?? retryable;
    } catch (e) {
      message = `HTTP ${resp.status} (invalid error body: ${e instanceof Error ? e.message : String(e)})`;
    }
    return new ApiError(resp.status, code, message, retryable);
  }
}
""")

# ── TypeScript response types ─────────────────────────────────────────────────

def ts_response_type(op):
    if op.no_content:
        return "void"
    schema = op.resp.get("content", {}).get("application/json", {}).get("schema", {})
    props  = schema.get("properties", {})
    if props and not schema.get("additionalProperties"):
        return go_name(op.op_id) + "Response"
    return "Record<string, unknown>"

def ts_response_interface(op):
    rtype = ts_response_type(op)
    if rtype in ("void", "Record<string, unknown>"):
        return ""
    schema = op.resp.get("content", {}).get("application/json", {}).get("schema", {})
    props   = schema.get("properties", {})
    fields  = []
    for fname, fschema in sorted(props.items()):
        ftype = fschema.get("type", "unknown")
        add   = fschema.get("additionalProperties")
        if ftype == "string":
            ts_type = "string"
        elif ftype == "boolean":
            ts_type = "boolean"
        elif ftype == "integer" or ftype == "number":
            ts_type = "number"
        elif ftype == "array":
            ts_type = "unknown[]"
        elif ftype == "object" and add:
            inner    = add.get("type", "unknown")
            inner_ts = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}.get(inner, "unknown")
            ts_type  = f"Record<string, {inner_ts}>"
        else:
            ts_type = "unknown"
        fields.append(f"  {fname}: {ts_type};")
    return f"export interface {rtype} {{\n" + "\n".join(fields) + "\n}\n"

interfaces = "".join(iface for op in ops if (iface := ts_response_interface(op)))

def path_expr_ts(op):
    if not op.path_params:
        return f'"{op.path}"'
    tpl = op.path
    for p in op.path_params:
        tpl = tpl.replace("{" + p + "}", "${encodeURIComponent(" + param_arg_name(p) + ")}")
    return f"`{tpl}`"

def ts_method(op):
    fn    = ts_name(op.op_id)
    rtype = ts_response_type(op)

    param_parts = []
    for p in op.path_params:
        param_parts.append(f"{param_arg_name(p)}: string")
    if op.has_body:
        param_parts.append("payload: Record<string, unknown>")
    for name, ptype in op.query_params:
        ts_type = "number" if ptype == "integer" else "string"
        param_parts.append(f"{param_arg_name(name)}?: {ts_type}")
    if op.secure:
        param_parts.append("apiKey?: string")
    params = ", ".join(param_parts)

    base_path_expr = path_expr_ts(op)
    body_lines = []
    if op.query_params:
        body_lines.append(f"    let path: string = {base_path_expr};")
        body_lines.append("    const q = new URLSearchParams();")
        for name, ptype in op.query_params:
            arg = param_arg_name(name)
            body_lines.append(f'    if ({arg} !== undefined) q.set("{name}", String({arg}));')
        body_lines.append('    if ([...q].length > 0) path += "?" + q.toString();')
        call_path_expr = "path"
    else:
        call_path_expr = base_path_expr

    method_upper = op.method.upper()
    body_arg     = "payload" if op.has_body else "undefined"
    api_key_expr = "apiKey ?? this.defaultApiKey" if op.secure else "undefined"

    doc_lines = [
        "  /**",
        f"   * {method_upper} {op.path} — {op.op_id.replace('_', ' ')}.",
    ]
    if op.secure:
        doc_lines.append("   * @param apiKey - Override the default API key for this call.")
    doc_lines.append("   */")
    doc_block = "\n".join(doc_lines)

    if rtype == "void":
        ret_type = "Promise<void>"
        call_line = f'    await this.requestVoid("{method_upper}", {call_path_expr}, {body_arg}, {api_key_expr});'
    else:
        ret_type = f"Promise<{rtype}>"
        call_line = f'    return this.request<{rtype}>("{method_upper}", {call_path_expr}, {body_arg}, {api_key_expr});'

    body_all = "\n".join(body_lines + [call_line])
    return (
        f"{doc_block}\n"
        f"  async {fn}({params}): {ret_type} {{\n"
        f"{body_all}\n"
        f"  }}"
    )

methods_ts = "\n\n".join(ts_method(op) for op in ops)

write(os.path.join(TS_DIR, "src", "client.ts"), ts_header + f"""
import {{ ApiError }} from "./errors";

{interfaces}
export interface ClientOptions {{
  /** Override the global fetch implementation (useful in tests). Defaults to globalThis.fetch. */
  fetch?: typeof globalThis.fetch;
  /** Default API key sent as {api_key_header} on authenticated requests. */
  apiKey?: string;
}}

/**
 * Client is a type-safe consumer SDK for the Crucible Gateway.
 * It uses the runtime's fetch with no additional runtime dependencies.
 */
export class Client {{
  private readonly baseURL: string;
  private readonly fetchImpl: typeof globalThis.fetch;
  private readonly defaultApiKey: string | undefined;

  constructor(baseURL: string, options: ClientOptions = {{}}) {{
    // Normalize baseURL: strip query, fragment, and credentials (mirrors Go client).
    let normalizedURL = baseURL;
    try {{
      const u = new URL(baseURL);
      u.search = "";
      u.hash = "";
      u.username = "";
      u.password = "";
      normalizedURL = u.toString();
    }} catch {{
      throw new TypeError(`crucible: invalid baseURL: ${{baseURL}}`);
    }}
    this.baseURL = normalizedURL.replace(/\\/+$/u, "");
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.defaultApiKey = options.apiKey;
  }}

{methods_ts}

  // request performs a JSON-in/JSON-out call and decodes the response body.
  // body === undefined means "no request body" (no Content-Type header, no
  // fetch body); this covers both bodyless GETs and bodyless authenticated
  // POSTs (e.g. a secret-rotation endpoint).
  private async request<T>(method: string, path: string, body: unknown, apiKey?: string): Promise<T> {{
    const headers: Record<string, string> = {{ Accept: "application/json" }};
    if (body !== undefined) {{
      headers["Content-Type"] = "application/json";
    }}
    if (apiKey) {{
      headers["{api_key_header}"] = apiKey;
    }}
    const resp = await this.fetchImpl(this.baseURL + path, {{
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    }});
    if (!resp.ok) {{
      throw await ApiError.fromResponse(resp);
    }}
    const ct = resp.headers.get("content-type") ?? "";
    if (!ct.includes("application/json")) {{
      throw new ApiError(resp.status, "UNKNOWN", `unexpected content-type: ${{ct}}`);
    }}
    return resp.json() as Promise<T>;
  }}

  // requestVoid is request's counterpart for no-content (204-style) responses:
  // it never touches resp.json(), since there is no body to decode.
  private async requestVoid(method: string, path: string, body: unknown, apiKey?: string): Promise<void> {{
    const headers: Record<string, string> = {{}};
    if (body !== undefined) {{
      headers["Content-Type"] = "application/json";
    }}
    if (apiKey) {{
      headers["{api_key_header}"] = apiKey;
    }}
    const resp = await this.fetchImpl(this.baseURL + path, {{
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    }});
    if (!resp.ok) {{
      throw await ApiError.fromResponse(resp);
    }}
  }}
}}
""")

# ── src/index.ts ──────────────────────────────────────────────────────────────
type_exports = ", ".join(
    t for op in ops
    if (t := ts_response_type(op)) not in ("Record<string, unknown>", "void")
)
type_export_line = (
    f'export type {{ ClientOptions{", " + type_exports if type_exports else ""} }} from "./client";\n'
)

# index.ts appends an extra comment (beyond ts_header) to make clear that the
# webhook re-export on the final line is also generator-produced, not a hand-edit.
# ts_header is shared with errors.ts and client.ts; the webhook note is index-specific.
index_webhook_note = (
    "// Webhook re-exports (last line) are emitted by this generator; "
    "edit gen-clients.sh and re-run — do not hand-edit.\n"
)
write(os.path.join(TS_DIR, "src", "index.ts"), ts_header + index_webhook_note + (
    f'export {{ Client }} from "./client";\n'
    f'{type_export_line}'
    f'export {{ ApiError }} from "./errors";\n'
    f'export type {{ ErrorBody }} from "./errors";\n'
    f'export {{ verifyWebhook, WebhookVerificationError, DEFAULT_TOLERANCE_MS, SIGNATURE_HEADER, TIMESTAMP_HEADER, WEBHOOK_EVENT_ID_HEADER, WEBHOOK_EVENT_TYPE_HEADER }} from "./webhook";\n'
))

# ── test/client.test.ts ───────────────────────────────────────────────────────

def ts_test_call_args(op, key_literal='"key"'):
    args = []
    for p in op.path_params:
        args.append(f'"test-{p}"')
    if op.has_body:
        args.append("{}")
    for name, ptype in op.query_params:
        args.append("undefined")
    if op.secure:
        args.append(key_literal)
    return args

def ts_test_method(op):
    fn    = ts_name(op.op_id)
    rtype = ts_response_type(op)

    test_path = op.path
    for p in op.path_params:
        test_path = test_path.replace("{" + p + "}", "test-" + p)

    schema = op.resp.get("content", {}).get("application/json", {}).get("schema", {}) if not op.no_content else {}
    props  = schema.get("properties", {}) if not op.no_content else {}

    if op.no_content:
        mock_status = 204
        mock_body = None
    else:
        mock_status = 200
        sample = {}
        for p_name in sorted(props.keys()):
            pschema = props[p_name]
            t = pschema.get("type")
            if t == "string":
                sample[p_name] = "ok"
            elif t == "object":
                sample[p_name] = {"db": "ok"}
            elif t in ("integer", "number"):
                sample[p_name] = 1
            elif t == "boolean":
                sample[p_name] = True
            elif t == "array":
                sample[p_name] = []
        if not sample and rtype == "Record<string, unknown>":
            sample = {"result": "ok"}
        mock_body = json.dumps(sample)

    call_args = ts_test_call_args(op)
    call = f'await c.{fn}({", ".join(call_args)})'

    first_str_prop = next((p for p in sorted(props.keys()) if props[p].get("type") == "string"), None) if props else None

    def mock_response_line(var_name):
        if op.no_content:
            return f'      return new Response(null, {{ status: {mock_status} }});'
        return (
            f'      return new Response(JSON.stringify({mock_body}), {{\n'
            f'        status: {mock_status}, headers: {{ "Content-Type": "application/json" }},\n'
            f'      }});'
        )

    lines = [
        f'describe("Client.{fn}", () => {{',
        f'  it("sends the expected request and handles the {mock_status} response", async () => {{',
        '    let capturedInit: RequestInit | undefined;',
        '    let capturedUrl: string | URL | Request | undefined;',
        '    const capFetch: typeof globalThis.fetch = async (url, init) => {',
        '      capturedUrl = url;',
        '      capturedInit = init;',
        mock_response_line("capturedInit"),
        '    };',
        '    const c = new Client("http://gw.test", { fetch: capFetch });',
        f'    const got = {call};',
        f'    assert.equal(String(capturedUrl), "http://gw.test{test_path}");',
        f'    assert.equal(capturedInit!.method, "{op.method.upper()}");',
    ]
    if op.secure:
        lines.append('    const hdrs = capturedInit!.headers as Record<string, string>;')
        lines.append(f'    assert.equal(hdrs["{api_key_header}"], "key");')
    if op.has_body:
        lines.append('    const reqBody = JSON.parse(capturedInit!.body as string);')
        lines.append('    assert.deepEqual(reqBody, {});')
    if op.no_content:
        lines.append('    assert.equal(got, undefined);')
    elif first_str_prop:
        lines.append(f'    assert.equal(got.{first_str_prop}, "ok");')
    elif rtype == "Record<string, unknown>":
        lines.append('    assert.equal((got as Record<string, unknown>)["result"], "ok");')
    else:
        lines.append('    assert.ok(got);')
    lines.append('  });')

    if op.secure:
        call_no_key_args = ts_test_call_args(op)[:-1]
        call_no_key = f'await c2.{fn}({", ".join(call_no_key_args)})'
        lines += [
            '',
            '  it("falls back to constructor apiKey when not provided", async () => {',
            '    let capturedInit2: RequestInit | undefined;',
            '    const capFetch2: typeof globalThis.fetch = async (_url, init) => {',
            '      capturedInit2 = init;',
            mock_response_line("capturedInit2"),
            '    };',
            '    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });',
            f'    {call_no_key};',
            '    const hdrs2 = capturedInit2!.headers as Record<string, string>;',
            f'    assert.equal(hdrs2["{api_key_header}"], "default-key");',
            '  });',
        ]
    lines.append('});')
    return "\n".join(lines)

ts_test_methods = "\n\n".join(ts_test_method(op) for op in ops)

# Query-encoding regression test: verifies typed query args are URL-encoded correctly.
query_encoding_test_ts = ""
if first_query_op:
    fn_q = ts_name(first_query_op.op_id)
    call_args_q = []
    for p in first_query_op.path_params:
        call_args_q.append(f'"test-{p}"')
    if first_query_op.has_body:
        call_args_q.append("{}")
    query_checks_ts = []
    for name, ptype in first_query_op.query_params:
        if ptype == "integer":
            call_args_q.append("2")
            query_checks_ts.append((name, "2"))
        else:
            call_args_q.append('"v"')
            query_checks_ts.append((name, "v"))
    if first_query_op.secure:
        call_args_q.append('"key"')
    call_q = f'await c.{fn_q}({", ".join(call_args_q)})'
    assertions = "\n".join(
        f'    assert.equal(url.searchParams.get("{name}"), "{val}");' for name, val in query_checks_ts
    )
    query_encoding_test_ts = "\n\n" + "\n".join([
        f'describe("Client.{fn_q} query encoding", () => {{',
        '  it("URL-encodes query parameters", async () => {',
        '    let capturedUrl: string | URL | Request | undefined;',
        '    const capFetch: typeof globalThis.fetch = async (u) => {',
        '      capturedUrl = u;',
        '      return new Response(JSON.stringify({}), { status: 200, headers: { "Content-Type": "application/json" } });',
        '    };',
        '    const c = new Client("http://gw.test", { fetch: capFetch });',
        f'    {call_q};',
        '    const url = new URL(String(capturedUrl));',
        assertions,
        '  });',
        '});',
    ])

# Error test uses first authenticated POST operation (guaranteed non-None after sys.exit check).
auth_ts_fn = ts_name(first_auth_post.op_id)
if first_auth_post.has_body:
    # payload is first param; omit apiKey (uses constructor default or undefined).
    auth_ts_call = f'() => c.{auth_ts_fn}({{}})'
else:
    auth_ts_call = f'() => c.{auth_ts_fn}()'

write(os.path.join(TS_DIR, "test", "client.test.ts"), ts_header + f"""\
import {{ describe, it }} from "node:test";
import assert from "node:assert/strict";
import {{ Client, ApiError }} from "../src/index";

{ts_test_methods}{query_encoding_test_ts}

describe("ApiError", () => {{
  it("is an instance of Error", () => {{
    const err = new ApiError(500, "TEST", "test error");
    assert.ok(err instanceof Error);
    assert.equal(err.message, "test error");
    assert.equal(err.code, "TEST");
    assert.equal(err.name, "ApiError");
  }});

  it("fromResponse parses error envelope", async () => {{
    const resp = new Response(
      JSON.stringify({{ error: {{ code: "QUOTA_EXCEEDED", message: "over limit", retryable: true }} }}),
      {{ status: 402 }},
    );
    const err = await ApiError.fromResponse(resp);
    assert.equal(err.code, "QUOTA_EXCEEDED");
    assert.equal(err.retryable, true);
    assert.equal(err.status, 402);
  }});

  it("fromResponse handles non-JSON body gracefully", async () => {{
    const resp = new Response("not json", {{ status: 503 }});
    const err = await ApiError.fromResponse(resp);
    assert.equal(err.code, "UNKNOWN");
    assert.equal(err.status, 503);
  }});

  it("throws ApiError with typed code on 401", async () => {{
    const c = new Client("http://gw.test", {{
      fetch: mockFetch(401, {{ error: {{ code: "UNAUTHORIZED", message: "bad key", retryable: false }} }}),
    }});
    await assert.rejects(
      {auth_ts_call},
      (err: unknown) => {{
        assert.ok(err instanceof ApiError);
        assert.equal(err.code, "UNAUTHORIZED");
        assert.equal(err.retryable, false);
        return true;
      }},
    );
  }});

  it("throws ApiError with retryable=true on 429", async () => {{
    const c = new Client("http://gw.test", {{
      fetch: mockFetch(429, {{ error: {{ code: "RATE_LIMITED", message: "slow down", retryable: true }} }}),
    }});
    await assert.rejects(
      {auth_ts_call},
      (err: unknown) => {{
        assert.ok(err instanceof ApiError);
        assert.equal(err.code, "RATE_LIMITED");
        assert.equal(err.retryable, true);
        return true;
      }},
    );
  }});
}});

function mockFetch(status: number, body: unknown): typeof globalThis.fetch {{
  return async (_url: string | URL | Request, _init?: RequestInit): Promise<Response> => {{
    return new Response(JSON.stringify(body), {{
      status,
      headers: {{ "Content-Type": "application/json" }},
    }});
  }};
}}
""")

print(f"Generated clients from {os.path.basename(SPEC_PATH)} ({title} {version})")
print(f"  Go:         {GO_DIR}")
print(f"  TypeScript: {TS_DIR}")
PYEOF

# Struct field alignment (json tag column widths) depends on the full set of
# field names/types in a struct, which this generator emits without tracking
# gofmt's alignment rules itself; gofmt is authoritative and already required
# (go 1.22+, see header), so let it do the alignment instead of duplicating
# its logic here. Scoped to exactly the files this generator writes — the
# hand-maintained webhook.go/webhook_test.go/webhook_internal_test.go in the
# same directory are untouched.
gofmt -w \
  "${REPO_ROOT}/clients/go/client.go" \
  "${REPO_ROOT}/clients/go/client_test.go" \
  "${REPO_ROOT}/clients/go/errors.go"
