// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { Client, ApiError } from "../src/index";

describe("Client.healthz", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"status": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.healthz();
    assert.equal(String(capturedUrl), "http://gw.test/healthz");
    assert.equal(capturedInit!.method, "GET");
    assert.equal(got.status, "ok");
  });
});

describe("Client.readyz", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"checks": {"db": "ok"}, "status": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.readyz();
    assert.equal(String(capturedUrl), "http://gw.test/readyz");
    assert.equal(capturedInit!.method, "GET");
    assert.equal(got.status, "ok");
  });
});

describe("Client.invokeEcho", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"result": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.invokeEcho({}, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/echo");
    assert.equal(capturedInit!.method, "POST");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    const reqBody = JSON.parse(capturedInit!.body as string);
    assert.deepEqual(reqBody, {});
    assert.equal((got as Record<string, unknown>)["result"], "ok");
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"result": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.invokeEcho({});
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.listErrors", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"data": [], "has_more": true, "limit": 1, "page": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.listErrors(undefined, undefined, undefined, undefined, undefined, undefined, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/errors");
    assert.equal(capturedInit!.method, "GET");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.ok(got);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"data": [], "has_more": true, "limit": 1, "page": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.listErrors(undefined, undefined, undefined, undefined, undefined, undefined);
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.listJobs", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"items": [], "total": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.listJobs(undefined, undefined, undefined, undefined, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/jobs");
    assert.equal(capturedInit!.method, "GET");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.ok(got);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"items": [], "total": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.listJobs(undefined, undefined, undefined, undefined);
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.getJob", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"billable_units": 1, "created_at": "ok", "error": {"db": "ok"}, "job_id": "ok", "result": {"db": "ok"}, "status": "ok", "units_label": "ok", "updated_at": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.getJob("test-id", "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/jobs/test-id");
    assert.equal(capturedInit!.method, "GET");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.equal(got.created_at, "ok");
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"billable_units": 1, "created_at": "ok", "error": {"db": "ok"}, "job_id": "ok", "result": {"db": "ok"}, "status": "ok", "units_label": "ok", "updated_at": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.getJob("test-id");
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.cancelJob", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"billable_units": 1, "created_at": "ok", "error": {"db": "ok"}, "job_id": "ok", "result": {"db": "ok"}, "status": "ok", "units_label": "ok", "updated_at": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.cancelJob("test-id", "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/jobs/test-id/cancel");
    assert.equal(capturedInit!.method, "POST");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.equal(got.created_at, "ok");
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"billable_units": 1, "created_at": "ok", "error": {"db": "ok"}, "job_id": "ok", "result": {"db": "ok"}, "status": "ok", "units_label": "ok", "updated_at": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.cancelJob("test-id");
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.listKeys", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"items": [], "total": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.listKeys(undefined, undefined, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/keys");
    assert.equal(capturedInit!.method, "GET");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.ok(got);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"items": [], "total": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.listKeys(undefined, undefined);
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.revokeKey", () => {
  it("sends the expected request and handles the 204 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(null, { status: 204 });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.revokeKey("test-id", "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/keys/test-id");
    assert.equal(capturedInit!.method, "DELETE");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.equal(got, undefined);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(null, { status: 204 });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.revokeKey("test-id");
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.rotateKey", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"key": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.rotateKey("test-id", {}, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/keys/test-id/rotate");
    assert.equal(capturedInit!.method, "POST");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    const reqBody = JSON.parse(capturedInit!.body as string);
    assert.deepEqual(reqBody, {});
    assert.equal(got.key, "ok");
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"key": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.rotateKey("test-id", {});
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.getUsage", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"breakdown": [], "cap": 1, "period_end": "ok", "period_start": "ok", "plan_id": "ok", "remaining": 1, "total_calls": 1, "total_units": 1, "used": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.getUsage("key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/usage");
    assert.equal(capturedInit!.method, "GET");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.equal(got.period_end, "ok");
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"breakdown": [], "cap": 1, "period_end": "ok", "period_start": "ok", "plan_id": "ok", "remaining": 1, "total_calls": 1, "total_units": 1, "used": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.getUsage();
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.listUsageEvents", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"data": [], "has_more": true, "limit": 1, "page": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.listUsageEvents(undefined, undefined, undefined, undefined, undefined, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/usage/events");
    assert.equal(capturedInit!.method, "GET");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.ok(got);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"data": [], "has_more": true, "limit": 1, "page": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.listUsageEvents(undefined, undefined, undefined, undefined, undefined);
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.listWebhookDeliveries", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"items": [], "total": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.listWebhookDeliveries(undefined, undefined, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/webhooks/deliveries");
    assert.equal(capturedInit!.method, "GET");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.ok(got);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"items": [], "total": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.listWebhookDeliveries(undefined, undefined);
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.listWebhookEndpoints", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"items": [], "total": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.listWebhookEndpoints(undefined, undefined, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/webhooks/endpoints");
    assert.equal(capturedInit!.method, "GET");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.ok(got);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"items": [], "total": 1}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.listWebhookEndpoints(undefined, undefined);
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.createWebhookEndpoint", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"active": true, "created_at": "ok", "id": "ok", "secret_hex": "ok", "subscribed_events": [], "url": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.createWebhookEndpoint({}, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/webhooks/endpoints");
    assert.equal(capturedInit!.method, "POST");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    const reqBody = JSON.parse(capturedInit!.body as string);
    assert.deepEqual(reqBody, {});
    assert.equal(got.created_at, "ok");
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"active": true, "created_at": "ok", "id": "ok", "secret_hex": "ok", "subscribed_events": [], "url": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.createWebhookEndpoint({});
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.deleteWebhookEndpoint", () => {
  it("sends the expected request and handles the 204 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(null, { status: 204 });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.deleteWebhookEndpoint("test-id", "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/webhooks/endpoints/test-id");
    assert.equal(capturedInit!.method, "DELETE");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.equal(got, undefined);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(null, { status: 204 });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.deleteWebhookEndpoint("test-id");
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.updateWebhookEndpointSubscription", () => {
  it("sends the expected request and handles the 204 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(null, { status: 204 });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.updateWebhookEndpointSubscription("test-id", {}, "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/webhooks/endpoints/test-id");
    assert.equal(capturedInit!.method, "PATCH");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    const reqBody = JSON.parse(capturedInit!.body as string);
    assert.deepEqual(reqBody, {});
    assert.equal(got, undefined);
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(null, { status: 204 });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.updateWebhookEndpointSubscription("test-id", {});
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.rotateWebhookEndpointSecret", () => {
  it("sends the expected request and handles the 200 response", async () => {
    let capturedInit: RequestInit | undefined;
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (url, init) => {
      capturedUrl = url;
      capturedInit = init;
      return new Response(JSON.stringify({"secret_hex": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.rotateWebhookEndpointSecret("test-id", "key");
    assert.equal(String(capturedUrl), "http://gw.test/v1/webhooks/endpoints/test-id/rotate-secret");
    assert.equal(capturedInit!.method, "POST");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
    assert.equal(got.secret_hex, "ok");
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"secret_hex": "ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.rotateWebhookEndpointSecret("test-id");
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("Client.listErrors query encoding", () => {
  it("URL-encodes query parameters", async () => {
    let capturedUrl: string | URL | Request | undefined;
    const capFetch: typeof globalThis.fetch = async (u) => {
      capturedUrl = u;
      return new Response(JSON.stringify({}), { status: 200, headers: { "Content-Type": "application/json" } });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    await c.listErrors("v", "v", "v", "v", 2, 2, "key");
    const url = new URL(String(capturedUrl));
    assert.equal(url.searchParams.get("from"), "v");
    assert.equal(url.searchParams.get("to"), "v");
    assert.equal(url.searchParams.get("operation"), "v");
    assert.equal(url.searchParams.get("code"), "v");
    assert.equal(url.searchParams.get("page"), "2");
    assert.equal(url.searchParams.get("limit"), "2");
  });
});

describe("Client.rotateKey optional body", () => {
  it("sends an empty JSON object when payload is not provided", async () => {
    let capturedInit: RequestInit | undefined;
    const capFetch: typeof globalThis.fetch = async (_url, init) => {
      capturedInit = init;
      return new Response(JSON.stringify({}), { status: 200, headers: { "Content-Type": "application/json" } });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    await c.rotateKey("test-id", undefined, "key");
    assert.equal(capturedInit!.body, "{}");
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["Content-Type"], "application/json");
  });
});

describe("ApiError", () => {
  it("is an instance of Error", () => {
    const err = new ApiError(500, "TEST", "test error");
    assert.ok(err instanceof Error);
    assert.equal(err.message, "test error");
    assert.equal(err.code, "TEST");
    assert.equal(err.name, "ApiError");
  });

  it("fromResponse parses error envelope", async () => {
    const resp = new Response(
      JSON.stringify({ error: { code: "QUOTA_EXCEEDED", message: "over limit", retryable: true } }),
      { status: 402 },
    );
    const err = await ApiError.fromResponse(resp);
    assert.equal(err.code, "QUOTA_EXCEEDED");
    assert.equal(err.retryable, true);
    assert.equal(err.status, 402);
  });

  it("fromResponse handles non-JSON body gracefully", async () => {
    const resp = new Response("not json", { status: 503 });
    const err = await ApiError.fromResponse(resp);
    assert.equal(err.code, "UNKNOWN");
    assert.equal(err.status, 503);
  });

  it("throws ApiError with typed code on 401", async () => {
    const c = new Client("http://gw.test", {
      fetch: mockFetch(401, { error: { code: "UNAUTHORIZED", message: "bad key", retryable: false } }),
    });
    await assert.rejects(
      () => c.invokeEcho({}),
      (err: unknown) => {
        assert.ok(err instanceof ApiError);
        assert.equal(err.code, "UNAUTHORIZED");
        assert.equal(err.retryable, false);
        return true;
      },
    );
  });

  it("throws ApiError with retryable=true on 429", async () => {
    const c = new Client("http://gw.test", {
      fetch: mockFetch(429, { error: { code: "RATE_LIMITED", message: "slow down", retryable: true } }),
    });
    await assert.rejects(
      () => c.invokeEcho({}),
      (err: unknown) => {
        assert.ok(err instanceof ApiError);
        assert.equal(err.code, "RATE_LIMITED");
        assert.equal(err.retryable, true);
        return true;
      },
    );
  });
});

function mockFetch(status: number, body: unknown): typeof globalThis.fetch {
  return async (_url: string | URL | Request, _init?: RequestInit): Promise<Response> => {
    return new Response(JSON.stringify(body), {
      status,
      headers: { "Content-Type": "application/json" },
    });
  };
}
