// Code generated by scripts/gen-clients.sh — DO NOT EDIT.
// Source: clients/openapi.json (Crucible Gateway 1.0.0)
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { Client, ApiError } from "../src/index";

function mockFetch(status: number, body: unknown): typeof globalThis.fetch {
  return async (_url: string | URL | Request, _init?: RequestInit): Promise<Response> => {
    return new Response(JSON.stringify(body), {
      status,
      headers: { "Content-Type": "application/json" },
    });
  };
}

describe("Client.healthz", () => {
  it("returns typed HealthzResponse on 200", async () => {
    const c = new Client("http://gw.test", { fetch: mockFetch(200, {"status": "ok"}) });
    const got = await c.healthz();
    assert.equal(got.status, "ok");
  });
});

describe("Client.readyz", () => {
  it("returns typed ReadyzResponse on 200", async () => {
    const c = new Client("http://gw.test", { fetch: mockFetch(200, {"checks": {"db": "ok"}, "status": "ok"}) });
    const got = await c.readyz();
    assert.equal(got.status, "ok");
  });
});

describe("Client.invokeEcho", () => {
  it("sends X-API-Key header and returns Record<string, unknown> on 200", async () => {
    let capturedInit: RequestInit | undefined;
    const capFetch: typeof globalThis.fetch = async (_url, init) => {
      capturedInit = init;
      return new Response(JSON.stringify({"result":"ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c = new Client("http://gw.test", { fetch: capFetch });
    const got = await c.invokeEcho({}, "key");
    assert.equal(got["result"], "ok");
    assert.ok(capturedInit, "capFetch was not called");
    const body = JSON.parse(capturedInit!.body as string);
    assert.deepEqual(body, {});
    const hdrs = capturedInit!.headers as Record<string, string>;
    assert.equal(hdrs["X-API-Key"], "key");
  });

  it("falls back to constructor apiKey when not provided", async () => {
    let capturedInit2: RequestInit | undefined;
    const capFetch2: typeof globalThis.fetch = async (_url, init) => {
      capturedInit2 = init;
      return new Response(JSON.stringify({"result":"ok"}), {
        status: 200, headers: { "Content-Type": "application/json" },
      });
    };
    const c2 = new Client("http://gw.test", { fetch: capFetch2, apiKey: "default-key" });
    await c2.invokeEcho({});
    const hdrs2 = capturedInit2!.headers as Record<string, string>;
    assert.equal(hdrs2["X-API-Key"], "default-key");
  });
});

describe("ApiError", () => {
  it("is an instance of Error", () => {
    const err = new ApiError(500, "TEST", "test error");
    assert.ok(err instanceof Error);
    assert.equal(err.message, "test error");
    assert.equal(err.code, "TEST");
    assert.equal(err.name, "ApiError");
  });

  it("fromResponse parses error envelope", async () => {
    const resp = new Response(
      JSON.stringify({ error: { code: "QUOTA_EXCEEDED", message: "over limit", retryable: true } }),
      { status: 402 },
    );
    const err = await ApiError.fromResponse(resp);
    assert.equal(err.code, "QUOTA_EXCEEDED");
    assert.equal(err.retryable, true);
    assert.equal(err.status, 402);
  });

  it("fromResponse handles non-JSON body gracefully", async () => {
    const resp = new Response("not json", { status: 503 });
    const err = await ApiError.fromResponse(resp);
    assert.equal(err.code, "UNKNOWN");
    assert.equal(err.status, 503);
  });

  it("throws ApiError with typed code on 401", async () => {
    const c = new Client("http://gw.test", {
      fetch: mockFetch(401, { error: { code: "UNAUTHORIZED", message: "bad key", retryable: false } }),
    });
    await assert.rejects(
      () => c.invokeEcho({}),
      (err: unknown) => {
        assert.ok(err instanceof ApiError);
        assert.equal(err.code, "UNAUTHORIZED");
        assert.equal(err.retryable, false);
        return true;
      },
    );
  });

  it("throws ApiError with retryable=true on 429", async () => {
    const c = new Client("http://gw.test", {
      fetch: mockFetch(429, { error: { code: "RATE_LIMITED", message: "slow down", retryable: true } }),
    });
    await assert.rejects(
      () => c.invokeEcho({}),
      (err: unknown) => {
        assert.ok(err instanceof ApiError);
        assert.equal(err.code, "RATE_LIMITED");
        assert.equal(err.retryable, true);
        return true;
      },
    );
  });
});
